### ISSUE TITLE
Misplaced TODO dialog when using keybinding

### ISSUE THREAD

**Issue by knight-corvi** [zagortenay333/cronomix#1]
There seems to be an issue when opening the TODO dialog using the keybinding. I'm using the [Dash to Panel](https://extensions.gnome.org/extension/1160/dash-to-panel/) and the [Panel](https://extensions.gnome.org/extension/708/panel-osd/) extensions. The dialog is being misplaced at the bottom:
![screenshot from 2017-06-20 21-06-53](https://user-images.githubusercontent.com/3454040/27366677-86b1f2ee-55fc-11e7-8299-6dae45305d09.png)
normal:
![screenshot from 2017-06-20 21-09-11](https://user-images.githubusercontent.com/3454040/27366712-b9744038-55fc-11e7-8248-dd953db0203b.png)

Is there anyway to move up the dialog or to autoadjust similar as to how the message tray does it?
![screenshot from 2017-06-20 21-10-35](https://user-images.githubusercontent.com/3454040/27366760-01dfa966-55fd-11e7-9d3c-f8857c26462e.png)

**Comment by zagortenay333** [comment]
Turns out that's a bug in dash-to-panel. Only the source alignment was a
bug on my part, and I fixed it in the latest commit. Will open a bug report
on dash-to-panel.

Bug report: https://github.com/jderose9/dash-to-panel/issues/200

**Comment by knight-corvi** [comment]
Alright, thank you
