### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by davidrojaslizama** [zagortenay333/cronomix#105]
Hi, I have the following message when i try to enable Time++

SyntaxError: class is a reserved identifier

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:239
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178
  main@resource:///org/gnome/shell/extensionPrefs/main.js:377
  @<main>:1
  

Thanks for any help

**Comment by zagortenay333** [comment]
You're probably using the wrong version of the extension. Reopen this issue if that's not the case.
