### ISSUE TITLE
break countdown never starts

### ISSUE THREAD

**Issue by nicoboni** [zagortenay333/cronomix#106]
Hi,

On my machine the pomodoro break timer never starts: the countdown is set to the defined break time (e.g.: 00:05:00) but it does not start. This happens either if the break time arrives on its own or if you click "take break".

The working timer works fine. 

Extension installed manually from github

**edit:** further investigation revealed that this only happens when you put something into "control todo time tracker by task id". If the field is empty the break time works as expected.

**Comment by fndercole** [comment]
Same here, on Ubuntu 19.04

I can confirm that 
> this only happens when you put something into "control todo time tracker by task id". If the field is empty the break time works as expected.

**Comment by zagortenay333** [comment]
I think this is fixed now. Let me know.
