### ISSUE TITLE
Pomodoro is not working in any way

### ISSUE THREAD

**Issue by ruasoliveira** [zagortenay333/cronomix#109]
Pomodoro is enabled in the "general" tab, in settings. However, its icon does not appear and, when clicking on it, in the panel, there are no option to set or switch to turn it on. It does not matter whether I choose to join menus into a single icon into panel, or if I leave them separate.

```
$ gnome-shell --version
GNOME Shell 3.28.4
$ cat /etc/issue
Ubuntu 18.04.2 LTS \n \l
$ uname -srm
Linux 4.18.0-25-generic x86_64
```

![timerpp_pomodoro_0](https://user-images.githubusercontent.com/2765975/61815305-57fe9780-ae20-11e9-8b65-fe2e36d85ecd.png)
![timerpp_pomodoro_1](https://user-images.githubusercontent.com/2765975/61815308-58972e00-ae20-11e9-8bac-fcf78548cb59.png)

**Comment by zagortenay333** [comment]
What version of timepp are you using?

**Comment by ruasoliveira** [comment]
Version 145. This is what the metadata file looks like:

```
{
  "_generated": "Generated by SweetTooth, do not edit", 
  "cache-file-format-version": {
    "alarms": 3, 
    "pomodoro": 3, 
    "stopwatch": 4, 
    "timer": 3, 
    "todo": 10
  }, 
  "description": "A todo.txt manager, time tracker, timer, stopwatch, pomodoro, and alarm clock", 
  "gettext-domain": "timepp", 
  "issues_url": "https://github.com/zagortenay333/timepp__gnome/issues", 
  "name": "Time ++", 
  "original-author": "https://github.com/zagortenay333", 
  "shell-version": [
    "3.24", 
    "3.26", 
    "3.28", 
    "3.30"
  ], 
  "translations_url": "https://github.com/zagortenay333/timepp__gnome/tree/master/data/po_files", 
  "url": "https://github.com/zagortenay333/timepp__gnome", 
  "uuid": "timepp@zagortenay333", 
  "version": 145
}
```

**Comment by zagortenay333** [comment]
Hmm what is that "generated by sweettooth" thing? Did you download from the gnome site? Try using the version from github: https://github.com/zagortenay333/timepp__gnome/releases

I can't really help you out since I don't use gnome at the moment.

**Comment by ruasoliveira** [comment]
Thanks, it is working flawlessly now! Yes, I had downloaded it from extensions.gnome.org
