### ISSUE TITLE
[Feature Request] Option to link task to a file/application.

### ISSUE THREAD

**Issue by cj-sv** [zagortenay333/cronomix#11]
First of all, great work on the extension.

I'm wondering if this is possible? Being able to open a file related to a task would be quite helpful for those managing a lot of files. I used to do this in Zim Wiki.

**Comment by zagortenay333** [comment]
Open file? You mean open the todo.txt file from the extension?

If so, I don't see why that's useful. This extension provides all the facilities to edit the tasks; it's not meant to be only used for viewing tasks.

**Comment by cj-sv** [comment]
Nah, I mean opening a document (or even a folder) associated with a task. Let's say you need to edit a spreadsheet later on, by linking the spreadsheet file to the task, you can open the file directly from reviewing the open tasks.

**Comment by zagortenay333** [comment]
Oh, you're talking about file uri's :smile: 

Yes, that's already possible, I just need to adjust the regex for it it seems. I thought that the regex was already working correctly.

**Comment by zagortenay333** [comment]
This is implemented now. The instructions are in the readme file: https://github.com/zagortenay333/timepp__gnome#todotxt-manager

Let me know if it works correctly.

**Comment by cj-sv** [comment]
Awesome, URLs, paths, and files work nicely except for files with 2 or more spaces within the file name.

~/Downloads/test\ singlespace - Works
~/Downloads/test\ two\ spaces - Does not work

![image](https://user-images.githubusercontent.com/11567756/28488509-35204caa-6ede-11e7-875c-d117ff959bba.png)

![image](https://user-images.githubusercontent.com/11567756/28488512-3ce27e86-6ede-11e7-9693-b296253316bc.png)

Btw might be easier to implement or use, I see some other applications like MPV and WINE use double quotes for "url with spaces".

**Comment by zagortenay333** [comment]
Using double quotes would be nightmarish..

This is fixed now.
