### ISSUE TITLE
Pomodoro doesn't work. It doesn't appear

### ISSUE THREAD

**Issue by lynxpardina** [zagortenay333/cronomix#111]
Great app. Congratulations. 

I am using Ubuntu 18.04 and the pomodoro part does not appear anywhere except in the configuration settings.
![Captura de pantalla de 2019-09-02 22-31-53](https://user-images.githubusercontent.com/13015957/64132667-c0527880-cdd1-11e9-94ad-f80dd45f827b.png)

As you can see the space appears but not the pomodoro. Any ideas?

**Comment by zagortenay333** [comment]
Are you using the version from github?

**Comment by lynxpardina** [comment]
I have installed it from gnome shell extensions, just from this link
https://extensions.gnome.org/extension/1238/time/
Do I need to install the one from github?


*Pepe*
about.me/lynxpardina

**Comment by lynxpardina** [comment]
Hi! I've installed the github version following your instructions and the extension shows the icon of error and cannot be activated.

**Comment by zagortenay333** [comment]
Did you download the correct version?

**Comment by lynxpardina** [comment]
I have downloaded the latest version on github instead of cloning it, following your instructions for manual install. 
It is updated for gnome-shell v 3.32 but I have checked mine and I have gnome-shell version 3.28.4

**Comment by zagortenay333** [comment]
For older version you can download one of the releases: https://github.com/zagortenay333/timepp__gnome/releases

**Comment by lynxpardina** [comment]
Ok! Thanks, now it works fine. Great.
Thank you very much!.

**Comment by zagortenay333** [comment]
Cheers.
