### ISSUE TITLE
Getting 'ERROR' when installing extension

### ISSUE THREAD

**Issue by josephhyatt** [zagortenay333/cronomix#112]
When I install the extension from [extensions.gnome.org](https://extensions.gnome.org/extension/1238/time/) I get an error.
![error](https://user-images.githubusercontent.com/22139956/64637589-fd61d080-d3b8-11e9-8e85-b5f4db5baab1.png)

**Comment by zagortenay333** [comment]
Does you gnome shell version match the extension's version?

**Comment by josephhyatt** [comment]
Yes, Im on gnome 3.28.2  
I download the 3.28 Shell Version

**Comment by zagortenay333** [comment]
Try downloading from github: https://github.com/zagortenay333/timepp__gnome/releases

**Comment by josephhyatt** [comment]
I tried that too. I followed your instructions and still not working. I atl + f2 and r for restart and nothing. Also restarted pc just in case and nothing.
![error1](https://user-images.githubusercontent.com/22139956/64643637-a7475a00-d3c5-11e9-81b5-5b268de79ea6.png)

**Comment by zagortenay333** [comment]
Type this into the terminal to see what the error is:
```
journalctl /usr/bin/gnome-shell -r
```

**Comment by josephhyatt** [comment]
`└─▪ journalctl /usr/bin/gnome-shell -r                                                                                                        
-- Logs begin at Sun 2019-09-01 09:23:46 PDT, end at Tue 2019-09-10 14:37:48 PDT. --                                                          
Sep 10 14:34:40 linux org.gnome.Shell.desktop[1466]: Window manager warning: Buggy client sent a _NE                                          
Sep 10 14:34:38 linux gnome-shell[1466]: Called enable_unredirect_for_screen while unredirection is                                           
Sep 10 14:34:31 linux gnome-shell[1466]: Called enable_unredirect_for_screen while unredirection is                                           
Sep 10 14:34:25 linux gnome-shell[1466]: Error looking up permission: GDBus.Error:org.freedesktop.po                                          
Sep 10 14:34:25 linux gnome-shell[1466]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem                                           
Sep 10 14:34:25 linux gnome-shell[1466]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem                                           
Sep 10 14:34:25 linux org.gnome.Shell.desktop[1466]: Window manager warning: Trying to re-add keybin                                          
Sep 10 14:34:25 linux gnome-shell[1466]: loading default theme (Adwaita)                                                                      
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE                                          
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE                                          
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE                                          
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE                                          
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE                                          
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE                                          
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE                                          
lines 1-23...skipping...                                                                                                                      
-- Logs begin at Sun 2019-09-01 09:23:46 PDT, end at Tue 2019-09-10 14:37:48 PDT. --                                                          
Sep 10 14:34:40 linux org.gnome.Shell.desktop[1466]: Window manager warning: Buggy client sent a _NET_                                        
Sep 10 14:34:38 linux gnome-shell[1466]: Called enable_unredirect_for_screen while unredirection is en                                        
Sep 10 14:34:31 linux gnome-shell[1466]: Called enable_unredirect_for_screen while unredirection is en                                        
Sep 10 14:34:25 linux gnome-shell[1466]: Error looking up permission: GDBus.Error:org.freedesktop.port                                        
Sep 10 14:34:25 linux gnome-shell[1466]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1                                        
Sep 10 14:34:25 linux gnome-shell[1466]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1                                        
Sep 10 14:34:25 linux org.gnome.Shell.desktop[1466]: Window manager warning: Trying to re-add keybindi                                        
Sep 10 14:34:25 linux gnome-shell[1466]: loading default theme (Adwaita)                                                                      
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (                                        
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (                                        
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (                                        
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (                                        
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (                                        
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (                                        
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (                                        
Sep 10 14:31:40 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed                                                
lines 1-24...skipping...                                                                                                                      
-- Logs begin at Sun 2019-09-01 09:23:46 PDT, end at Tue 2019-09-10 14:37:48 PDT. --
Sep 10 14:34:40 linux org.gnome.Shell.desktop[1466]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp o
Sep 10 14:34:38 linux gnome-shell[1466]: Called enable_unredirect_for_screen while unredirection is enabled.
Sep 10 14:34:31 linux gnome-shell[1466]: Called enable_unredirect_for_screen while unredirection is enabled.
Sep 10 14:34:25 linux gnome-shell[1466]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocat
Sep 10 14:34:25 linux gnome-shell[1466]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.78/org/ayatana/NotificationItem/livepat
Sep 10 14:34:25 linux gnome-shell[1466]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.78/org/ayatana/NotificationItem/softwar
Sep 10 14:34:25 linux org.gnome.Shell.desktop[1466]: Window manager warning: Trying to re-add keybinding "switch-next-audio-output".
Sep 10 14:34:25 linux gnome-shell[1466]: loading default theme (Adwaita)
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:41 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:41 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:40 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: g_array_unref: assertion 'array' failed
Sep 10 14:31:38 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:38 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:36 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:36 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:36 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed
Sep 10 14:31:36 linux gnome-shell[1466]: st_theme_context_get_for_stage: assertion 'CLUTTER_IS_STAGE (stage)' failed
Sep 10 14:31:36 linux gnome-shell[1466]: g_object_get: assertion 'G_IS_OBJECT (object)' failed`

**Comment by josephhyatt** [comment]
There's a lot of errors. I'll take some screenshots

**Comment by josephhyatt** [comment]
![09-10-2019](https://user-images.githubusercontent.com/22139956/64652611-24c89580-d3d9-11e9-9912-bda1d17d6b9b.png)
![09-10-2019_1](https://user-images.githubusercontent.com/22139956/64652612-24c89580-d3d9-11e9-935d-5753025ce9ba.png)
![09-10-2019_2](https://user-images.githubusercontent.com/22139956/64652613-24c89580-d3d9-11e9-81ce-16be49b9e173.png)
![09-10-2019_3](https://user-images.githubusercontent.com/22139956/64652614-24c89580-d3d9-11e9-984b-08ac19b48df3.png)
![09-10-2019_4](https://user-images.githubusercontent.com/22139956/64652615-25612c00-d3d9-11e9-9d3b-4b4b301fc024.png)
![09-10-2019_5](https://user-images.githubusercontent.com/22139956/64652616-25612c00-d3d9-11e9-8ab4-598f70e354b3.png)

**Comment by josephhyatt** [comment]
Any ideas?

**Comment by zagortenay333** [comment]
I don't know what it is precisely. All you can try is commenting this call out: https://github.com/zagortenay333/timepp__gnome/blob/1d4429449a05b61eaab327504a2050eb9dcc9ae2/extension.js#L245-L248

The assertion to `st_theme_context_get_for_stage` went off. I guess because `global.stage` doesn't work anymore? No idea.

**Comment by josephhyatt** [comment]
That didn't work.. Well if you ever get this issue fixed let me know. It sounds like a good extension.

**Comment by grzekru** [comment]
Same issue on Debian Sid.
Works fine on Arch Linux.

**Comment by altsalt** [comment]
By the way, I had this problem, so I removed the extension and downgraded to the 3.24-3.30 version on GitHub. So far things appear functional. That being said, my extension manager is asking for an update and I'm actively avoiding it as my guess is that functionality would break.

**Comment by zagortenay333** [comment]
No clue what to do with this issue so closing it.
