### ISSUE TITLE
Unsupported gnome 3.34

### ISSUE THREAD

**Issue by Lord-Guckavin** [zagortenay333/cronomix#113]
watch out for the shell theme adjustments on this update

Here's the JournalCtl output that I thought that was relevant. 
https://gist.github.com/Lord-Guckavin/4b60d3e2f652d08a276b4c402f93ea30

**Comment by mathben** [comment]
"actor" is deprecated, I cannot find the documentation about it, or what to do.
I found this code : https://github.com/jwrdegoede/TopIcons-plus/commit/454e3dc157ea1d91fffb6c0b3728ecdee6206860

**Comment by Lord-Guckavin** [comment]
Yeah I just swiped a chunk of my the log that I thought might help but wasn't fully sure. I've jumped back to gnome 3.32 for the mean time.

**Comment by zagortenay333** [comment]
From what I can tell, you just have to remove the actor prop. Not on gnome-shell, so I can't do much for now.

**Comment by mbroedl** [comment]
This might help with interpreting the debugs?
https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/559

**Comment by Lord-Guckavin** [comment]
Cheers Karneds and Zagortenay, massive legends the both of you.
