### ISSUE TITLE
Timer doesn't appear in the panel

### ISSUE THREAD

**Issue by nguxx** [zagortenay333/cronomix#114]
in Ubuntu 18.04.3.
Show in only one menu is not working also, i still have 3 menus with the timer empty

**Comment by zagortenay333** [comment]
Are you using the correct version of the extension?

**Comment by zagortenay333** [comment]
I can't replicate this on 3.28:
![Screenshot_2019-07-24_11-36-15](https://user-images.githubusercontent.com/11144630/67634019-5cbb6780-f8b7-11e9-8df9-6f4c8b053e09.png)
