### ISSUE TITLE
alarm appears multiple(around 15) times

### ISSUE THREAD

**Issue by Bzahov98** [zagortenay333/cronomix#119]
alarm appears multiple(around 15) times and crashes the whole system Ububtu 18.04 sometimes on system startup.
**journalctl info:**

` gnome-shell[9323]: JS ERROR: Gio.IOErrorEnum: Error opening file /home//.local/share/gnome-shell/extensions/timepp@za
                                           Timepp<._load_stylesheet@/home/bzahov/.local/share/gnome-shell/extensions/timepp@zagortenay333/extens
                                           wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                           Timepp<._on_theme_changed@/home/bzahov/.local/share/gnome-shell/extensions/timepp@zagortenay333/exten
                                           wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                           Timepp<._init/<@/home/bzahov/.local/share/gnome-shell/extensions/timepp@zagortenay333/extension.js:24
дек 02 16:22:40 bobo gnome-shell[9323]: JS ERROR: Gio.IOErrorEnum: Error opening file /home/bzahov/.local/share/gnome-shell/extensions/timepp@za
                                           Timepp<._load_stylesheet@/home/bzahov/.local/share/gnome-shell/extensions/timepp@zagortenay333/extens
                                           wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                           Timepp<._on_theme_changed@/home/bzahov/.local/share/gnome-shell/extensions/timepp@zagortenay333/exten
                                           wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                           Timepp<._init/<@/home/bzahov/.local/share/gnome-shell/extensions/timepp@zagortenay333/extension.js:24
`

` g_object_ref: assertion 'G_IS_OBJECT (ob
дек 02 16:24:11 bobo gnome-shell[9323]: g_object_ref: assertion 'G_IS_OBJECT (ob
дек 02 16:24:11 bobo gnome-shell[9323]: g_object_ref: assertion 'G_IS_OBJECT (ob
дек 02 16:24:11 bobo gnome-shell[9323]: g_object_ref: assertion 'G_IS_OBJECT (ob
дек 02 16:24:11 bobo gnome-shell[9323]: g_object_ref: assertion 'G_IS_OBJECT (ob
дек 02 16:24:11 bobo gnome-shell[9323]: g_object_ref: assertion 'G_IS_OBJECT (ob
дек 02 16:24:11 bobo gnome-shell[9323]: g_object_ref: assertion 'G_IS_OBJECT (ob
дек 02 16:24:11 bobo gnome-shell[9323]: g_object_ref: assertion 'G_IS_OBJECT (ob
дек 02 16:24:11 bobo gnome-shell[9323]: JS ERROR: Error: Argument 'file' (type i
                                           loadTheme@resource:///org/gnome/shell
                                           Timepp<._load_stylesheet@/home/bzahov
                                           wrapper@resource:///org/gnome/gjs/mod
                                           Timepp<._init/<@/home/bzahov/.local/s
`

**Comment by zagortenay333** [comment]
You still using this extension? If so, what are the version you are using. What extension and what gnome version?
