### ISSUE TITLE
Start timer for specific task via command line

### ISSUE THREAD

**Issue by Algram** [zagortenay333/cronomix#12]
Is there a way to start a timer for a specific task from the command line?

I want to start a timer everytime I switch my workspace.

**Comment by zagortenay333** [comment]
I might implement a dbus iface. Not sure that I want to though, but I'll look into it.

**Comment by zagortenay333** [comment]
It doesn't seem like it's possible to know when the workspaces have changed from within a bash script. Even if I implemented the abilit to pause/start the time-tracker from the cli, you still wouldn't be able to get what you want.

Do you know if it's possible to do this?

**Comment by Algram** [comment]
@zagortenay333 It is possible with `xdotool get_desktop`.
So it is possible to track it that way if your extension provides the interface. It would be super useful because you could automate a lot of the time tracking for tasks.

**Comment by zagortenay333** [comment]
I added the dbus interface. The instructions are in the README.

Let me know if it works correctly.

**Comment by Algram** [comment]
@zagortenay333 Wow that was super fast! It is working perfectly. Thanks a ton!

**Comment by zagortenay333** [comment]
Cheers.

**Comment by zagortenay333** [comment]
@Algram In case anybody needs it too, I got a cool script for controlling the time-tracker:
https://github.com/zagortenay333/dotfiles/blob/master/scripts/tracker_control

**Comment by tekvsakdan** [comment]
I'm also using this. I have created global shortcuts for running the script.

```
#!/bin/bash

let "t = 60 * $1"
gdbus call \
        --session \
        --dest org.gnome.Shell \
        --object-path /timepp/zagortenay333/Timer \
        --method timepp.zagortenay333.Timer.start $t

```

**Comment by zagortenay333** [comment]
@tekvsakdan I just updated the timer's dbus api because of the newly introduced timer presets. Might wanna check it out.
