### ISSUE TITLE
GitHub & others kanban boards & alarm

### ISSUE THREAD

**Issue by razcore-rad** [zagortenay333/cronomix#120]
Hello there! Thanks again for this very wonderful extension, I'm using it extensively to track my work so I'm very grateful for your work, thanks a lot!

Now to the business. Have you ever considered being able to connect to GitHub project boards/Trello kanban boards  etc. types of services? I assume this would be a huge deal and work load. I'd be willing to help out if you got any starting point. Sadly I didn't find great resources on how to build Gnome extensions so if you got any please do share.

One other idea. You think it's possible to trigger time tracking for a specific task from an external source? I'm thinking I'd like to manage them to some extent via `neovim` which I use 99% for my work - `SpaceVim` to be more precise.

**Comment by zagortenay333** [comment]
Hey, glad you like the extension.

This extension is in low maintenance already. No way I'm adding any online services. I wouldn't accept any pull requests either.

As for your other point, the extension has a dbus API so you can use that.  
For example, there is a little script you can use to start tracking when switching workspaces (on Xorg): https://github.com/zagortenay333/timepp__gnome/blob/master/dbus/scripts/time_tracker_control

**Comment by razcore-rad** [comment]
Cool, thanks for the quick response and info
