### ISSUE TITLE
Pomodoro does not appear; v145 gnome-shell-3.28

### ISSUE THREAD

**Issue by samuelps** [zagortenay333/cronomix#122]
There is no icon for pomodoro appearing on the top bar, even when show option is activated in config.

Only a white space between alarm and stopwatch with a blank popup when you click on it

**Comment by ruisen** [comment]
> There is no icon for pomodoro appearing on the top bar, even when show option is activated in config.
> 
> Only a white space between alarm and stopwatch with a blank popup when you click on it

Have the same problem.

**Comment by altsalt** [comment]
Issue still exists in gnome-shell-3.30

```
:~$ uname -srvmo
Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

:~$ dpkg -l|grep gnome-shell
ii  chrome-gnome-shell                    10.1-5 
ii  gnome-shell                           3.30.2-11~deb10u1
ii  gnome-shell-common                    3.30.2-11~deb10u1
ii  gnome-shell-extensions                3.30.1-1

:~$ cat ~/.local/share/gnome-shell/extensions/timepp@zagortenay333/metadata.json |grep '"version"'
  "version": 145
```

Does the gnome-shell-pomodoro package need to be installed?

**Comment by lordvcs** [comment]
Same issue on ubuntu 18.04.4 and gnome shell 3.28.2
![image](https://user-images.githubusercontent.com/6374881/78874037-5dad1380-7a69-11ea-96ff-c94926eb7007.png)
![Screenshot from 2020-04-09 13-50-13](https://user-images.githubusercontent.com/6374881/78874054-643b8b00-7a69-11ea-959d-203e17b56afd.png)

**Comment by altsalt** [comment]
By the way, I removed the extension and downgraded to the 3.24-3.30 version on GitHub. So far things appear functional. That being said, my extension manager is asking for an update and I'm actively avoiding it as my guess is that functionality would break.

**Comment by zagortenay333** [comment]
I just tried this on gnome 3.28 and can't reproduce it. Judging by the comment above I have a feeling people are using the wrong version of this extension. For gnome 3.28 you need to use the 3.24--3.28 version.
