### ISSUE TITLE
Some icons disappear 

### ISSUE THREAD

**Issue by murshid1988** [zagortenay333/cronomix#125]
Some icons disappear when you return from a locked screen. Mostly the stop watch disappears.

**Comment by altsalt** [comment]
Having the same problem. I've tried changing all of the "Show in separate menu" settings to no avail.

```
:~$ uname -srvmo
Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

:~$ dpkg -l|grep gnome-shell
ii  chrome-gnome-shell                    10.1-5 
ii  gnome-shell                           3.30.2-11~deb10u1
ii  gnome-shell-common                    3.30.2-11~deb10u1
ii  gnome-shell-extensions                3.30.1-1

:~$ cat ~/.local/share/gnome-shell/extensions/timepp@zagortenay333/metadata.json |grep '"version"'
  "version": 145
```

**Comment by altsalt** [comment]
By the way, I removed the extension and downgraded to the 3.24-3.30 version on GitHub. So far things appear functional. That being said, my extension manager is asking for an update and I'm actively avoiding it as my guess is that functionality would break.

**Comment by zagortenay333** [comment]
Are you using the correct version of this extension? For gnome 3.30 you have to use the 3.34--3.30 version from github.
