### ISSUE TITLE
Fails to load on GNOME 3.36.0

### ISSUE THREAD

**Issue by johnnybubonic** [zagortenay333/cronomix#130]
The extension now no longer loads.

**Comment by zagortenay333** [comment]
Are you using the version from github?

**Comment by johnnybubonic** [comment]
The extension or GNOME? I'm using the extension version that's on https://extensions.gnome.org/, version 152.

**Comment by johnnybubonic** [comment]
Just tried a direct clone from this git repo and it works, but I'd prefer to use one from extensions.gnome.org because update notifications. Can you please promote this one to the GNOME extensions directory?

**Comment by zagortenay333** [comment]
There's other bugs that can't make it work on 3.36 yet.
