### ISSUE TITLE
[feature request] Persistent traking in Screen Lock

### ISSUE THREAD

**Issue by wirehiker** [zagortenay333/cronomix#131]
Hi, first of all thank you for developing such a great application.
My workflow involves moving from computer to other activities that don't involve the computer. While I'm not sitting at the pc I definitely want the to lock the screen and turn it off. I noticed that the Todo/Time Tracker stops when the screen is locked, which unfortunately defeats the purpose of the app. I imagine that others with a similar workflow could encounter the same problem. Would be possible to add a toggle for time tracking while the screen is locked down?
I know that you have already pointed out the problem in the readme. But still I wanted to let you know that some people care about this app.
Thank you in advance.

**Comment by zagortenay333** [comment]
I'm not gonna do this. If somebody else wants to do it, the relevant procedure is: https://github.com/zagortenay333/timepp__gnome/blob/master/sections/todo/time_tracker.js#L177

There's some edge cases. For example, the date changes while being locked.
