### ISSUE TITLE
[Gnome 3.36] sound and notifications not working

### ISSUE THREAD

**Issue by iamriyasmusafir** [zagortenay333/cronomix#137]
no sound and notifications
installed github latest version
ubuntu 20.04 with gnome .36.1

**Comment by iamriyasmusafir** [comment]
no sound and notifications
installed github latest version
ubuntu 20.04 with gnome .36.1

**Comment by danfulf** [comment]
Can confirm same issue on Fedora 32 gnome 3.36.2

**Comment by zagortenay333** [comment]
Should be fixed now. Let me know whether it works.
