### ISSUE TITLE
[GNOME 3.36] Bug lockscreen

### ISSUE THREAD

**Issue by MrBobFreeman** [zagortenay333/cronomix#139]
Github latest version.
Gnome 3.36 on ubuntu 20.04 and manjaro too.
Breaks down style, after locking the screen, And not working unlock.

**Comment by tflori** [comment]
Same problems here on manjaro with gnome 3.36...

After unlock I get a second unlock and sometimes the gnome-shell restarts. I'm not sure if I'm running the latest version but I will have a look now.

**Comment by tflori** [comment]
No, also the dev-master version is broken. I would like to help but I have no idea about gnome shell extension development and I'm always lost when I try to find out how to debug an extension.

**Comment by tflori** [comment]
when I see it right this fixes it:
```diff
Index: extension.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- extension.js	(revision 34ae477a51267cc1e85992a80cf85a1a7b7005c1)
+++ extension.js	(date 1592146643000)
@@ -570,7 +570,7 @@
 
         // reload theme
         Main.reloadThemeResource();
-        Main.loadTheme();
+        //Main.loadTheme();
 
         Mainloop.idle_add(() => this.theme_change_signal_block = false);
     }
```

you might want to give it a try...

The thing is: I don't know why `Main.loadTheme()` gets executed. Also when I execute it through looking glass it crashes.

**Comment by MrBobFreeman** [comment]
This did not solve the problem. Whatever Thank you!

**Comment by ignoxx** [comment]
Got the same issue, and was wondering for quite a while why the hell my lock screen is bugged as hell, after reinstalling and heavy research I've found nothing!

Tried to check today if one of my extensions breaks anything, and that's how I got here :D

Really nice extension, hope it gets fixed soon :)

That's how my desktop looks like after locking my screen
![Screenshot from 2020-06-14 13-32-14](https://user-images.githubusercontent.com/20191569/85212340-fc030280-b351-11ea-8d47-7285fadf4f68.png)

**Comment by dseebacher** [comment]
Same here on Fedora with Gnome 3.36.2.

This might help:

```
get@resource:///org/gnome/shell/ui/environment.js:287:29
AlarmEditor@/home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:538:9
alarm_editor@/home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:254:25
_on_edit@/home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:771:23
AlarmItem/<@/home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:701:101
connect_release/<@/home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/lib/signal_manager.js:62:48
Jun 21 13:15:33 localhost.localdomain gnome-shell[137451]: Usage of object.actor is deprecated for CheckBox
get@resource:///org/gnome/shell/ui/environment.js:287:29
AlarmEditor@/home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:539:9
alarm_editor@/home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:254:25
_on_edit@/home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:771:23
AlarmItem/<@/home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:701:101
connect_release/<@/home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/lib/signal_manager.js:62:48
Jun 21 13:15:37 localhost.localdomain gnome-shell[137451]: Object St.BoxLayout (0x557e59aa41a0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Jun 21 13:15:37 localhost.localdomain gnome-shell[137451]: clutter_actor_destroy: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jun 21 13:15:37 localhost.localdomain gnome-shell[137451]: == Stack trace for context 0x557e52d6f6b0 ==
Jun 21 13:15:37 localhost.localdomain gnome-shell[137451]: #0   557e53b30ac8 i   /home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:807 (2416f309fe98 @ 51)
Jun 21 13:15:37 localhost.localdomain gnome-shell[137451]: #1   557e53b30a38 i   /home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:303 (2416f309ae98 @ 148)
Jun 21 13:15:37 localhost.localdomain gnome-shell[137451]: #2   557e53b30958 i   resource:///org/gnome/gjs/modules/core/_signals.js:133 (2cb3c7a34c0 @ 427)
Jun 21 13:15:37 localhost.localdomain gnome-shell[137451]: #3   557e53b308a8 i   /home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:569 (2416f309f5b0 @ 17)
Jun 21 13:15:57 localhost.localdomain gnome-shell[137451]: Usage of object.actor is deprecated for Timepp
get@resource:///org/gnome/shell/ui/environment.js:287:29
destroy@/home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/extension.js:607:9
disable@/home/xxx/.local/share/gnome-shell/extensions/timepp@zagortenay333/extension.js:649:12
_callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:107:32
```

**Comment by sne4ky** [comment]
Hi, same problem here with Gnome 3.36 and Manjaro. This trace might help:
```
JS ERROR: Error: Argument 'file' (type interface) may not be null
loadTheme@resource:///org/gnome/shell/ui/main.js:428:19 
load_stylesheet@/home/marcos/.local/share/gnome-shell/extensions/timepp@zagortenay333/extension.js:573:14
_init/<@/home/marcos/.local/share/gnome-shell/extensions/timepp@zagortenay333/extension.js:237:38
```

**Comment by zexiangliu** [comment]
> when I see it right this fixes it:
> 
> ```diff
> Index: extension.js
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> --- extension.js	(revision 34ae477a51267cc1e85992a80cf85a1a7b7005c1)
> +++ extension.js	(date 1592146643000)
> @@ -570,7 +570,7 @@
>  
>          // reload theme
>          Main.reloadThemeResource();
> -        Main.loadTheme();
> +        //Main.loadTheme();
>  
>          Mainloop.idle_add(() => this.theme_change_signal_block = false);
>      }
> ```
> 
> you might want to give it a try...
> 
> The thing is: I don't know why `Main.loadTheme()` gets executed. Also when I execute it through looking glass it crashes.

even though it may not solve the real problem, as a temporary solution, this fixes the unlock issue on my laptop.

**Comment by eviawriter** [comment]
> when I see it right this fixes it:
> 
> ```diff
> Index: extension.js
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> --- extension.js	(revision 34ae477a51267cc1e85992a80cf85a1a7b7005c1)
> +++ extension.js	(date 1592146643000)
> @@ -570,7 +570,7 @@
>  
>          // reload theme
>          Main.reloadThemeResource();
> -        Main.loadTheme();
> +        //Main.loadTheme();
>  
>          Mainloop.idle_add(() => this.theme_change_signal_block = false);
>      }
> ```
> 
> you might want to give it a try...
> 
> The thing is: I don't know why `Main.loadTheme()` gets executed. Also when I execute it through looking glass it crashes.

This error was bugging me on 2 pc's. Finally found that it was this extension that was causing the problems.

I think disabling Main.loadTheme() works because the extension doesn't get disabled when the screen gets locked. It's because of this error: 'Usage of object.actor is deprecated'. 

To fix it, you'll need to edit line 607 in .local/share/gnome-shell/extensions/timepp@zagortenay333/extension.js:

```diff 
--- this._update_menu_arrow(this.actor);
+++ this._update_menu_arrow((this instanceof Clutter.Actor) ? this : this.actor);
```
On line 290 you could do the same, although I don't know if it's necessary or not:
```diff
--- this._update_menu_arrow(this.actor);
+++ this._update_menu_arrow((this instanceof Clutter.Actor) ? this : this.actor);
```
Note: I'm not really a developer or so, thus I have no idea if this breaks anything else :) Use at your own risk!

**Comment by zagortenay333** [comment]
Should be fixed now.
