### ISSUE TITLE
github issues as todo list

### ISSUE THREAD

**Issue by ktsaou** [zagortenay333/cronomix#14]
Hi,

Just found this extension. Nicely done!

Probably like you, I have several github repos full of issues.
It would be perfect if we could have our todo list fetched from the github repo issues that are assigned to us...

**Comment by zagortenay333** [comment]
Srry but no.

This will stay a todo.txt manager only; I have no intention of adding more complexity for something that is barely semantically related (issue tracker != todo list).

I could at most only show the issue's title as the todo.txt format doesn't allow multiline texts nor markup. You wouldn't have the comments nor would be able to interact with it in any meaningful way, so most people would end up using their respective issue tracker anyway.
