### ISSUE TITLE
Bug Time ++

### ISSUE THREAD

**Issue by mpavesi** [zagortenay333/cronomix#140]
Time ++, bugs after block screen, and Pomodoro not working on Gnome Debian 10

**Comment by zagortenay333** [comment]
Duplicate low effort issue...

**Comment by GithubUser699** [comment]
@mpavesi 
If you still need to get that working, follow this: https://github.com/zagortenay333/timepp__gnome/issues/155#issuecomment-867881720

I had the same issue, now it works as expected.
