### ISSUE TITLE
[GNOME 3.36] Stats not displaying anything

### ISSUE THREAD

**Issue by rishFilet** [zagortenay333/cronomix#141]
After logging time with pomodoro and time tracker the stats screen just shows three white blocks and nothing else.
![Screenshot from 2020-07-07 17-46-17](https://user-images.githubusercontent.com/28996036/86847121-d415dd80-c079-11ea-8239-8720ecc58312.png)

**Comment by zagortenay333** [comment]
This should be fixed now.
