### ISSUE TITLE
Alarms menu overflows screen when many added

### ISSUE THREAD

**Issue by jakubpawlina** [zagortenay333/cronomix#145]
### Problem
Alarms menu overflows screen when there are many alarms added. There is no way to see all alarms (scrolling not possible).

### Environment
Ubuntu 20.10 (GNOME 3.38)

### Idea for possible solution
Set max height of menu and use scroll for overflow event. 

### Screenshot
![problem](https://user-images.githubusercontent.com/29257057/98866881-f081b680-246d-11eb-95b1-e4a75067d9ca.png)

**Comment by zagortenay333** [comment]
Fixed.
