### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by nielsvl95** [zagortenay333/cronomix#146]
Hey
I did a translation to the dutch (Nederlands) language
In attachment you can find the .po file for dutch

Thanks for this gnome extension!

[nl.zip](https://github.com/zagortenay333/timepp__gnome/files/5538510/nl.zip)

**Comment by zagortenay333** [comment]
It doesn't seem you created that file correctly. You didn't fill in the "plural form" field and you also only have the translated strings in that file but not the original ones.
