### ISSUE TITLE
Kanban board example of todo.txt file.

### ISSUE THREAD

**Issue by belkevglaz** [zagortenay333/cronomix#147]
Hi.
Unfortunately, could not configure kanban board to view correctly tasks in this board.
From documentation I take s string `kan:*main|(A),(B),(C)|(D),(E),(F)|(G)` and tried to add new task within one of columns. As result - new task present in file, but nothing in extension view column. 
Could you please provide a simple todo.txt file example with kanban extension columns and several tasks in these columns ( as in a picture from readme)
Extension installed on Ubuntu 20.04 with Gnome version 3.36.3
Thanks a lot.

**Comment by zagortenay333** [comment]
There is an example todo. It's here: https://github.com/zagortenay333/timepp__gnome/tree/master/data

The string you showed above will only show tasks that have a priority added on them. You need to add a kitchen sink column to "collect" the reminaing tasks.

**Comment by belkevglaz** [comment]
Nice. Great example. Thanks a lot
