### ISSUE TITLE
Request: Custom actions on pomodoro completion 

### ISSUE THREAD

**Issue by indigoviolet** [zagortenay333/cronomix#148]
Thanks for this beautiful app. 

One feature that would be super useful is to trigger a custom actions on Pomodoro completion - for example this could be a logging script that tracks stats.

**Comment by zagortenay333** [comment]
I don't take feature requests. This project is in low maintaince.

**Comment by indigoviolet** [comment]
Thanks. If anyone else is interested in this, you can look into https://github.com/zagortenay333/timepp__gnome/blob/master/dbus/scripts/examples#L3  -- there are emitted events that can be monitored and scripted against.
