### ISSUE TITLE
Todo-list sorting.

### ISSUE THREAD

**Issue by Vaesper** [zagortenay333/cronomix#15]
Wanted to bring up two points about this, figured I'd throw them in together, then they can be separated out if needed.

First: a small bug report. When sorting the todo-list by due date ascending, items without a due date are shown first, rather than the expected "most urgent tasks at the top".

Second: a bigger feature request. I've taken to using Simpletask on Android, and I absolutely love the fine-grained sorting system there. Any chance of getting something like that in Time++?

**Comment by zagortenay333** [comment]
The due date sorting is now fixed.

What does that sorting system look like?

**Comment by Vaesper** [comment]
![screenshot of Simpletask sorting](https://i.imgur.com/yqRLWSM.png)

Note: the threshold date is [described here](https://github.com/ginatrapani/todo.txt-cli/wiki/Todo.sh-Add-on-Directory#future-tasks), very useful way for getting what you don't need to worry about/can't currently work on out of your face, amongst other things a pretty good way to note down "ideas for some day when you have time" without getting clutter in your immediate todolist. But supporting that should be a separate issue, just thought I'd give that some context.

**Comment by zagortenay333** [comment]
And how does that work? Is it attempting to sort by all criteria?

**Comment by Vaesper** [comment]
From top to bottom, first sort by "is completed", then - for items where that is the same - by "threshold date in future", then by list, then by due date, etc.

**Comment by zagortenay333** [comment]
Maybe I'm just dense, but I don't understand how that is supposed to work. If I sort by priority, then by creation date, how is that useful?

```
(A) 2017-01-03 asdf
(B) 2017-01-02 asdf
(C) 2017-01-01 asdf
```

**Comment by Vaesper** [comment]
Well as you can see in my screenshot, my sorting logic works like:
* First, bubble all completed items to bottom.
* Then, bubble all future tasks (with start/threshold date in future) to bottom (they sit above completed but below everything else).
* Then sort by list (list is simpletask's name for "context" since the author considers it to be more appropriate conceptually). It also performs grouping on this level (don't know how the logic works to determine this).
* Then sort by due date, ie. within every list/context I will see the most urgent items first.
* Then sort by priority. The reason I don't sort by priority first is that these are colorcoded so highly visible anyway.

The rest (tag = conceptually broader name for project) is things I don't really care about in sorting so the order is arbitrary for me.

**Comment by zagortenay333** [comment]
Yeah, I don't like this at all. Sorting according to 2+ criteria looks extremely confusing to me, because one criteria can nullify another.

In my example above, if I say sort by priority descending and then sort by creation date ascending, the creation dates will end up in descending order.

If I do end up implementing some sort of more 'nuanced' sorting mechanism, it won't look like this.

Looking at some of the individual criteria, what is the purpose of alphabetical sorting and what does sorting by context/project mean?

**Comment by Vaesper** [comment]
Well, it's essentially just a compound sort key. In your example, priority is the primary sort key, creation date is secondary. If that doesn't make sense as a sorting order, then use a different one :P In the current state of Time++, a user is only allowed to choose the primary sort key (with a limited selection) with no control over the rest of the sorting logic. I agree that finegrained control over the sorting may be an advanced feature, and not what everyone needs/should be on by default.

On the other hand, todo.txt is a way to organize and get/keep overview of what one needs to do, and as my todolist has grown I've found that the UX of having to apply filters to regain the overview I was lacking in the unfiltered view is causing some friction in my experience. Simpletask has solved this for me with the finegrained sorting control, but maybe it is overkill. Perhaps my needs would be (mostly) met if there was a way to sort/group by context.

**Comment by zagortenay333** [comment]
But in my example, the 'secondary key' is completely meaningless since it's nullified by the first key.

Is the logic supposed to be to sort by priority, and if two tasks happen to have the same priority, sort by creation date? Or sort by creation date, and if two tasks have the same creation date, sort by priority?
If so, I guess that makes some sense, but it doesn't look too useful to me.

What does sorting my context mean? I don't understand that.

**Comment by Vaesper** [comment]
In your example the "secondary key" is only nullified because you have only 1 item with (A) priority. I personally use (A) priority for many items, but if your workflow is different then you would need a different sorting logic than I would. In any case, having control over the secondary keys should not cause a regression over the situation over not having this control - it may just not provide benefits for every single usecase.

The logic is supposed to be "sort by primary sort key, and if two tasks happen to have the same value in that, sort by secondary sort key, if two tasks happen to have the same value in both, sort by tertiary sort key, etc etc".

Sorting by context means that I want to see my `@@supermarket` items listed together, and my `@@home` items listed together and my `@email` items listed together - if a task has multiple contexts, I think the logic used in Simpletask is to use the one that appears first alphabetically. With experimentation I've found that symbols are sorted before letters, so items that are in my `@buy` context and in my `@@supermarket` context will appear separate from my `@buy @@homeimprovement` tasks (`@buy` is a more broad context that I mainly use for filtering purposes).

**Comment by zagortenay333** [comment]
I implemented the same sorting mechanism with the latest commit. After using it for a while I actually like it. :smile: 

I also added 3 more sorting criteria: by completed, by context, by project.
When a task has multiple contexts/projects only the first context/project that appears will be used.

You can rearrange the sort criteria via mouse by drag-and-drop or via keyboard by focusing a sort icon and then `ctrl` + `up-arrow`/`down-arrow`.

Let me know if it works well.

**Comment by zagortenay333** [comment]
@Vaesper, regarding that threshold extension; you can already achieve that effect using the recurrence extension since recurring tasks that are completed are hidden in timepp.
Say you want the task to appear on `2017-10-23`:

``` sh
# One of the ways to do it is to make a new task that is already completed and
# set the year of creation to last year, set the month of creation to October,
# set 23d in the rec extension, and 12m as the increment.
#
# I.e., recur one year after October last year on the 23rd.

x 2000-01-01 2016-10-01 rec:23d-12m asdf
 ```
Do you think this is good enough?

**Comment by Vaesper** [comment]
@zagortenay333 sorry for late response - been away ;) Sorting looks good, will try out your suggestion with recurrence to filter out "future tasks".

**Comment by zagortenay333** [comment]
Cheers.
