### ISSUE TITLE
set sound uri

### ISSUE THREAD

**Issue by qebrow** [zagortenay333/cronomix#151]
Please fix the sound play.
In `lib/sound_player.js` is method `set_sound_uri`.
In this method is line `this.playbin.uri = sound_uri;`, but it doesn't work on my computer.
After this line I was add the line `this.playbin.set_property('uri', sound_uri);`, and after reboot of my computer it works for me.
Tested on Gnome 3.30.2 Debian GNU/Linux 10 (buster).
Thank you.

**Comment by peter-lyons-kehl** [comment]
Thank you for Time++.

I can't reproduce this error. The provided .ogg sounds play well on the current Manjaro with the newest GNOME 43.1.

**Comment by zagortenay333** [comment]
Closing because the new version of the extension has a simpler approach to playing sound.
