### ISSUE TITLE
I selected a pdf instead of todo.txt and the extension doesn't work anymore

### ISSUE THREAD

**Issue by gagudelo-aplyca** [zagortenay333/cronomix#152]
Even when reinstalled, all the info, i.e. alarms, stays there, including the pdf that's braking the extension.

Where do I reset the extension state, to be able to start from zero?.

**Comment by zagortenay333** [comment]
No clue. I guess reinstall it. Cache files for your alarms and other things are in: `~/.cache/timepp_gnome_shell_extension`. I don't exactly remember whether you have to back them up before reinstalling the extension.

If you wanna bother you can open a  terminal and type:
```
journalctl /usr/bin/gnome-shell -r | less
```
See if there are any errors related to timepp in there.

**Comment by zagortenay333** [comment]
Oh I just noticed you already reinstalled the extension. The todo files you opened are stored in `~/.cache/timepp_gnome_shell_extension/timepp_todo.json` . Just edit or delete this file.

**Comment by gagudelo-aplyca** [comment]
This was it. It solved it. Thank you @zagortenay333 .

I have a suggestion. Make the counter of tasks be consistent with filtering. I.e. if I filter tasks by @some_tag, I'd like the counter to show me the count of the tasks filtered only. Maybe you can make it an option.
![image](https://user-images.githubusercontent.com/77411095/106529130-f8268980-64b7-11eb-90c2-3e51711c45d9.png)

Great extension. Have a nice day.

**Comment by zagortenay333** [comment]
Glad it worked. As for the counter, I won't probably add features to this extension anymore. It's mostly in low maintainance.
