### ISSUE TITLE
show lap time in stopwatch (request for comments before I create pull request)

### ISSUE THREAD

**Issue by benwiz** [zagortenay333/cronomix#153]
I realize you're not taking feature requests so I will make the changes myself. I am asking here if you have any requirements in order so that my pull request fits your preferences.

My needs are simple. I want to display the current lap's elapsed time in the gnome panel either along side of or instead of the total time. For example `01:24:41 (00:05:12)`. Anything beyond that is excess and I will only do them if you or someone else requests it. **Is this a feature you would merge?**

It's not important to me, but since I'd like this merged, I will add a configuration to the settings window. I'm unsure if that will take the form of a new toggle or a new select drop down or additions to the `format` drop down. **Do you have a preference for the configuration?**

Since you store the string format time in `this.cache.laps` I am planning on storing the actual time value in something like `this.cache.laps_raw` rather than changing or parsing `this.cache.laps`. **Is adding another property to `cache` okay with you?**

**Comment by zagortenay333** [comment]
I'm not taking any pull requests either. I don't want to have to maintain and test new features.
