### ISSUE TITLE
Pomodoro icon missing and pop-out menu is blank in Gnome-shell v3.30

### ISSUE THREAD

**Issue by aurovrata** [zagortenay333/cronomix#155]
What an extension!  Impressive functionality, thank you!

When I enable the Pomodoro from the settings, a blank space appear to the right of the  'add file' icon.  When I click on that blank space a pop-out menu appears which is also blank (see screenshot below).
![Screenshot from 2021-02-20 17-22-47](https://user-images.githubusercontent.com/2766577/108594498-61573980-73a0-11eb-9b86-b2aa072df375.png)

**Comment by GithubUser699** [comment]
I have that too.
I only needed the pomodoro option, but https://extensions.gnome.org/extension/53/pomodoro/ only throws an error...

Did you manage to solve that issue @aurovrata? If so, how did you solve it?

**Comment by aurovrata** [comment]
this issue is still open

**Comment by GithubUser699** [comment]
Okay, I solved it.
I previously installed this extension from https://extensions.gnome.org/extension/1238/time/ but this is updated and seems to be buggy (see your bug report).

### What I did to make it work

1. Uninstall time++, if it's installed
2. I had to reboot my computer
3. Go to the [release](https://github.com/zagortenay333/timepp__gnome/releases) section here on github
4. Choose v3.24--v3.30 and [download the zip](https://github.com/zagortenay333/timepp__gnome/archive/refs/tags/v3.24--v3.30.zip)
5. Extract zip, rename the folder you got to _timepp@zagortenay333_
6. Move it to /home/YOUR_USER_NAME/.local/share/gnome-shell/extensions/
7. Reboot computer
8. Go to gnome tweaks and activate time++


Testet on Debian GNU/Linux 10 (buster), Gnome shell 3.30.2.

Now pomodoro also works. You could try to update this extension now, but this should introduce the very same bug again.

**Comment by gurkan-er** [comment]
> Okay, I solved it. I previously installed this extension from https://extensions.gnome.org/extension/1238/time/ but this is updated and seems to be buggy (see your bug report).
> ### What I did to make it work
> 
>     1. Uninstall time++, if it's installed
> 
>     2. I had to reboot my computer
> 
>     3. Go to the [release](https://github.com/zagortenay333/timepp__gnome/releases) section here on github
> 
>     4. Choose v3.24--v3.30 and [download the zip](https://github.com/zagortenay333/timepp__gnome/archive/refs/tags/v3.24--v3.30.zip)
> 
>     5. Extract zip, rename the folder you got to _timepp@zagortenay333_
> 
>     6. Move it to /home/YOUR_USER_NAME/.local/share/gnome-shell/extensions/
> 
>     7. Reboot computer
> 
>     8. Go to gnome tweaks and activate time++
> 
> 
> Testet on Debian GNU/Linux 10 (buster), Gnome shell 3.30.2.
> 
> Now pomodoro also works. You could try to update this extension now, but this should introduce the very same bug again.

I tested it on Zorin Os 15.3, gnome 3.30. Works great, thank you!
There is no release package here, so I downloaded v140 from [this page](https://extensions.gnome.org/extension/1238/time/?c=125292)

**Comment by zagortenay333** [comment]
Fixed.
