### ISSUE TITLE
Timer text not properly scaled in full screen mode

### ISSUE THREAD

**Issue by raffaelemancuso** [zagortenay333/cronomix#156]
If you activate "Show seconds", set up a timer and click on the square to bring the timer full screen, the text is cut off, and is displayed like "00:0..." with 3 dots at the end.

The stopwatch instead works correctly. The font is scaled down and the entire text is contained in the screen without being cut off.

**Comment by zagortenay333** [comment]
The new version of the extension lets you pick the size of the clock manually so closing.
