### ISSUE TITLE
How to write properly task in order to connect "Pomodoro" with task (task_id)

### ISSUE THREAD

**Issue by acapai** [zagortenay333/cronomix#158]
Hello,
I'm new on Linux and I'm beginner in "code" , "programmation" and so on. I read all the "Readme" file in order to understand how to write properly task (I saw "task_id:string" but I didn't success to write properly) in order to connect time tracker task "play icon" in todo/time tracker with Pomodoro (and vice versa). 

Example of what I would like to do (if possible): I write task_id in Pomodoro and when I start pomodoro the task present in todo with the same task_id  is also launched

Please could I get an example txt file or could you explain me how to connect both actions described ?

Thank you.
Have good day
Andria

**Comment by zagortenay333** [comment]
If I remember correctly, in a task you add a task_id extension like this: `(A) Do that thing. task_id:Batman`

Then in the pomodoro settings (the one in the panel menu) you add the id of the task: `Batman`.

Now when you start a pomodoro, any task that has `task_id:Batman` in it will start time tracking.

**Comment by mastoj** [comment]
If I follow this, how do I see that that the time tracking has started?

**Comment by zagortenay333** [comment]
The same way you know when you manually press the play button. There will be an indicator in the panel thaat the task is running. Orange I think.

**Comment by mastoj** [comment]
I got it working with `tracker_id:string`, not `task_id:string`.



`

**Comment by acapai** [comment]
Thank you all !
