### ISSUE TITLE
Can I somehow have two kanban boards with the same columns?

### ISSUE THREAD

**Issue by mastoj** [zagortenay333/cronomix#161]
If I define something like

```
h:1 kan:*Work|+todo|+in_progress|+done
h:1 kan:Home|+todo|+in_progress|+done
```

All items marked with `+tooo` will be in both boards. Is there a ways so I only see "Work" items on the "work board", and "Home" items on the "home board"?

I can definitely live without it, but just want to make sure I don't miss anything obvious.

**Comment by mastoj** [comment]
I think I found what I needed. 

Using the definition

```
h:1 kan:*My_board|@todo|@in_progress|@done
```

and then add `+project` to the items I can just apply filter per project to "switch" between projects.

**Comment by zagortenay333** [comment]
If I remember correctly, items are added to kanban columns from left to right. As soon as an item can go into a column it gets placed there. It cannot be in 2 different columns at the same time.

You can reorder columns by dragging them with the mouse. Then the the items will be redistributed.

**Comment by zagortenay333** [comment]
Note there is a special string you can add to a kanban column `(_)` to make it catch all completed tasks. You don't need a `@done` tag.
