### ISSUE TITLE
Support gnome 3.40

### ISSUE THREAD

**Issue by mathben** [zagortenay333/cronomix#162]
New version of gnome 3.40, it's not supported actually.

**Comment by stice2k** [comment]
A simple version bump seems to do the trick, no issues so far:

1. Open ~/.local/share/gnome-shell/extensions/timepp@zagortenay333/metadata.json (different path when installed globally)
2. Change L11: "shell-version" to: ```"shell-version": ["3.36", "3.38", "40"],```
3. Restart gnome ```ALT + F2``` and ```"r"```

Gnome shell versioning changed (40 instead of 3.40)

**Comment by zagortenay333** [comment]
This is fixed now.
