### ISSUE TITLE
Error with new upgrade (but old version was working)

### ISSUE THREAD

**Issue by steve-biggs-fox** [zagortenay333/cronomix#166]
Hello! Great app BTW - I use it everyday :)

I just got a notification for a new upgrade of this app. I installed it via Gnome extensions. New version reports as "error" in Gnome extensions and app is no longer available in my OS. Old version was working fine.

**Comment by steve-biggs-fox** [comment]
OK, it's working now but I had to restart my computer. This is the only extension out of about 20 that I just upgraded that required a restart. Would be better if it worked without the need for a restart please. Still, overall, great app. Thanks :)

**Comment by zagortenay333** [comment]
No clue what happened.
