### ISSUE TITLE
Latest update didn't resulted in error "Invalid object type 'GtkStackPage'"

### ISSUE THREAD

**Issue by mastoj** [zagortenay333/cronomix#169]
I just tried to update to the latest version and everything stopped working. The error message is:

> Gtk.BuilderError: /home/tomas/.local/share/gnome-shell/extensions/timepp@zagortenay333/data/prefs.ui:21:1 Invalid object type 'GtkStackPage'
> 
> Stack trace:
>   Settings@/home/tomas/.local/share/gnome-shell/extensions/timepp@zagortenay333/prefs.js:23:22
>   buildPrefsWidget@/home/tomas/.local/share/gnome-shell/extensions/timepp@zagortenay333/prefs.js:562:20
>   _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
>   OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
>   asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
>   run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
>   main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
>   run@resource:///org/gnome/gjs/modules/script/package.js:222:19
>   start@resource:///org/gnome/gjs/modules/script/package.js:206:8
>   @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
>   

I'm running pop os with the following OS info:

> NAME="Pop!_OS"
> VERSION="20.10"
> ID=pop
> ID_LIKE="ubuntu debian"
> PRETTY_NAME="Pop!_OS 20.10"
> VERSION_ID="20.10"
> HOME_URL="https://pop.system76.com"
> SUPPORT_URL="https://support.system76.com"
> BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
> PRIVACY_POLICY_URL="https://system76.com/privacy"
> VERSION_CODENAME=groovy
> UBUNTU_CODENAME=groovy
> LOGO=distributor-logo-pop-os
>

**Comment by hkockerbeck** [comment]
I see the same problem on Ubuntu 20.04 LTS with GNOME Shell 3.36.9. The extension can't be updated, and after I uninstalled it, it can't be installed again (bright red "Error" on https://extensions.gnome.org/local/). If I try to open the settings anyway, I get an error similar to what mastoj wrote:

```
Gtk.BuilderError: /home/henning/.local/share/gnome-shell/extensions/timepp@zagortenay333/data/prefs.ui:21:1 Invalid object type 'GtkStackPage'

Stack trace:
  Settings@/home/henning/.local/share/gnome-shell/extensions/timepp@zagortenay333/prefs.js:22:22
  buildPrefsWidget@/home/henning/.local/share/gnome-shell/extensions/timepp@zagortenay333/prefs.js:578:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

I've found [a similar bugreport](https://github.com/sereneblue/gnome-shell-extension-colosseum/issues/1) for a different extension. The maintainer there answered that that extension only supported GNOME 40. I'm not that up to speed on current Gtk, maybe GtkStackPage isn't available on older versions of GNOME Shell?

**Comment by zagortenay333** [comment]
The master branch of this extension only supports gnome 40 now. For 3.36 and 3.38 see: https://github.com/zagortenay333/timepp__gnome/tags
