### ISSUE TITLE
Version 157 is not working on Gnome 3.38.3

### ISSUE THREAD

**Issue by zandao** [zagortenay333/cronomix#170]
I was using version 156 on Gnome 3.38.3 (ubuntu) and when I upgraded to version 157 it stopped working. No error messages, just not working. Downgrading to version 156 solved the problem.

**Comment by zagortenay333** [comment]
The new version only supports gnome 40.

**Comment by zandao** [comment]
Since metadata.json still has the line "shell-version"    : ["3.36", "3.38", "40"] in it, extensions.gnome.org still reports this extension has an update for version 3.38 of Gnome (and it probably also reports the same to Gnome 3.36 users).

**Comment by zagortenay333** [comment]
Ahh, good point! I didn't think of removing those.

**Comment by zagortenay333** [comment]
Should be fixed now. Let me know if it doesn't work.
