### ISSUE TITLE
Kaban not work

### ISSUE THREAD

**Issue by rtsantanna** [zagortenay333/cronomix#171]
I can create tasks in Kanban, but I cannot move tasks from one status to another.

Dragging from one column to the other (Done to Inprogress), but it doesn't stay, and goes back to the first column when released.
Below, I put my todo.txt file

x 2021-06-22 kan:*main|Todo|inprogress|done
INC000004828131 @inprogress
echo PASSWORD | pam-keyring-tool -su
Recriar o disco da 253 @done
Encriptar o disco da DBC20
Verificar storage account do credimob
Empiricus
#inprogress: Inicio das +Férias \n due:2021-07-05

**Comment by zagortenay333** [comment]
Those are all kitchen sink columns, so the leftmost one gets all the tasks. You need to write `kan:*main|@Todo|@inprogress|@done`. If you don't have a @Todo then, make the Todo column be the last one: `kan:*main|@inprogress|@done|Todo`
