### ISSUE TITLE
Pomodoro and Timer resets when system gets locked

### ISSUE THREAD

**Issue by rama-2402** [zagortenay333/cronomix#173]
When the timer or pomodoro is running and if the system locks due to screen inactivity or if i manually lock the system the timer resets. I'm using Pop!_OS 21.04.

**Comment by zagortenay333** [comment]
All extensions get disabled when the screen is locked. Can't do anything about it. There is a warning about this in the README.

**Comment by rama-2402** [comment]
sorry my bad. Thank you for the quick response though. Much appreciated. BTW love the extension...it's helped with my productivity so much :)
