### ISSUE TITLE
Tasks disappeared when moving from todo.txt to done.txt 

### ISSUE THREAD

**Issue by maidenone** [zagortenay333/cronomix#18]
Here is what i have tested:
1. settings:
done file is specified as "done.txt"
todo file is specified as "todo.txt"

2. create a task, verify that task exists in todo.txt
3. log some time on task
4. check task as done, then clean tasks, make sure to select "archive to done and remove".
5. task is removed from todo.txt but done.txt is still empty.

BTW, thank you for an awesome plugin!

**Comment by zagortenay333** [comment]
Ah, that was a nasty typo. Should be fixed now. Thx for catching that. 

Let me know if it works correctly.
