### ISSUE TITLE
Error loading extension

### ISSUE THREAD

**Issue by aurovrata** [zagortenay333/cronomix#19]
I am using the latest Master branch version (12/09/2017) and get an 'error loading extension' in Gnome Shell 3.22.2,

I checked the system journal for the error:

`sudo journactl /usr/bin/gnome-shell`

and found 1 warnings & 1 error

```
JS WARNING: [~/.local/share/gnome-shell/extensions/timepp@zagortenay333/extension.js 202]: anonymous function does not always return a value
JS ERROR: Exception in callback for signal: extension-found: SyntaxError: illegal character @ ~/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/timer.js:34
```

**Comment by zagortenay333** [comment]
This extension doesn't support 3.22. Only 3.24 and 3.26.
