### ISSUE TITLE
Show milliseconds in stopwatch

### ISSUE THREAD

**Issue by anupam207** [zagortenay333/cronomix#2]
First and foremost, thank you for this beautiful extension.
An option to show milliseconds in stopwatch section would come in handy for precise time tracking.

**Comment by zagortenay333** [comment]
Thx.

Will look into it.

**Comment by zagortenay333** [comment]
This is done with 5c50855445dd41428ae98452de742ef630619f53

Let me know if it works correctly. Note you have to install the version of this extension from github to use it. It takes a lot of time for the gnome-shell extensions site to pick up.

**Comment by anupam207** [comment]
works fine! 💯
