### ISSUE TITLE
Consider supporting the todo.txt extension: threshold dates

### ISSUE THREAD

**Issue by smichel17** [zagortenay333/cronomix#22]
The extension is formatted like the due date extension, but with `t:` as the prefix instead of `due:`. Eg, `t:2017-09-19`.

Its function is to postpone tasks that you want to appear in your list at a later date. For example, I add my homework for the entire semester, and then set a threshold date for the days it will be assigned. Sorting by threshold date is also super useful (for tasks with no threshold date, use the creation date instead).

If you'd like to play around with threshold dates, the Android app [Simpletask](https://f-droid.org/packages/nl.mpcjanssen.simpletask/) has this feature, and it's honestly the best feature of the app (I manage my todo list using it almost exclusively, mostly because of threshold dates).

**Comment by zagortenay333** [comment]
The reason that I haven't implemented it yet is because the recurrence extension of Time++ is powerful enough to give you this. It may take a while to get used to though.

By default a completed recurring task is not shown in Time++.  
Say you want the task to appear on `2017-10-23`:

``` sh
# One of the ways to do it is to make a new task that is already completed and
# set the year of creation to last year, set the month of creation to October,
# set 23d in the rec extension, and 12m as the increment.
#
# I.e., recur one year after October last year on the 23rd.

x 2000-01-01 2016-10-01 rec:23d-12m asdf
 ```
With that said, I will probably implement the `t:` extension just so that your todo.txt file remains compatible with most other todo.txt managers.

**Comment by smichel17** [comment]
> With that said, I will probably implement the t: extension just so that your todo.txt file remains compatible with most other todo.txt managers.

Thank you!

> The reason that I haven't implemented it yet is because the recurrence extension of Time++ is powerful enough to give you this. It may take a while to get used to though.

Wouldn't your example also cause the task to recur the following year, the year after that, etc? It also says it disables the `due:` extension, which is a deal-breaker in my use case. Finally, I'm a little confused how your implementation of the `rec:` extension interacts with archival to `done.txt` (but, that's pretty tangential to this issue and not that important to me).

**Comment by zagortenay333** [comment]
> Wouldn't your example also cause the task to recur the following year, the year after that, etc?

Yeah it would, but you could disable it afterwards. Or if the task is complete, remove it.

Recurring tasks can only be archived 'manually'. I.e., click on the edit icon and archive button.

**Comment by zagortenay333** [comment]
This is implemented now. Let me know if it works.

**Comment by smichel17** [comment]
Great, thank you very much!
