### ISSUE TITLE
Unresponsive desktop after loading a todo file containing an url

### ISSUE THREAD

**Issue by he7d3r** [zagortenay333/cronomix#26]
After I installed the extension from
https://extensions.gnome.org/extension/1238/time/
on Ubuntu 17.10, with GNOME Shell 3.26.1, my desktop become unresponsive and I was not able to click anywhere. The same problem happened with the version currently available on GitHub. I had to delete the folder `~/.local/share/gnome-shell/extensions/timepp@zagortenay333` from the console before I could use the machine again.

**Comment by zagortenay333** [comment]
Can't help you if you don't give me a way to reproduce this.

When it crashes, check the output of:
```
journalctl /usr/bin/gnome-shell -r
```

**Comment by he7d3r** [comment]
```
-- Logs begin at Sat 2017-10-21 15:07:57 -02, end at Sat 2017-10-21 15:41:31 -02. --
out 21 15:40:35 u gnome-shell[5417]: Error looking up permission: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.impl.portal.PermissionStore was not provided by any .service files
out 21 15:40:34 u gnome-shell[5417]: Some code accessed the property 'Client' on the module 'dbusMenu'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
out 21 15:40:34 u gnome-shell[5417]: Some code accessed the property 'SNIStatus' on the module 'appIndicator'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
out 21 15:40:34 u org.gnome.Shell.desktop[5417]: Window manager warning: "XF86RFKill" is not a valid accelerator
out 21 15:40:34 u gnome-shell[5417]: Some code accessed the property 'IconCache' on the module 'iconCache'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
out 21 15:40:34 u gnome-shell[5417]: Some code accessed the property 'IconActor' on the module 'appIndicator'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
out 21 15:40:34 u gnome-shell[5417]: Some code accessed the property 'IndicatorStatusIcon' on the module 'indicatorStatusIcon'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
out 21 15:40:34 u gnome-shell[5417]: Some code accessed the property 'connectSmart' on the module 'util'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
out 21 15:40:34 u gnome-shell[5417]: Some code accessed the property 'StatusNotifierItem' on the module 'interfaces'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
out 21 15:40:34 u gnome-shell[5417]: Some code accessed the property 'AppIndicator' on the module 'appIndicator'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
out 21 15:40:34 u gnome-shell[5417]: [AppIndicatorSupport-DEBUG] Registering StatusNotifierItem :1.68/org/ayatana/NotificationItem/software_update_available
out 21 15:40:34 u gnome-shell[5417]: Some code accessed the property 'Logger' on the module 'util'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
out 21 15:40:34 u gnome-shell[5417]: WARNING: addSignalMethods is replacing existing [0x563607b46cb0 Gjs_ShowAppsIcon.dash-item-container] emit method
out 21 15:40:34 u gnome-shell[5417]: WARNING: addSignalMethods is replacing existing [0x563607b46cb0 Gjs_ShowAppsIcon.dash-item-container] disconnect method
out 21 15:40:34 u gnome-shell[5417]: WARNING: addSignalMethods is replacing existing [0x563607b46cb0 Gjs_ShowAppsIcon.dash-item-container] connect method
out 21 15:40:34 u gnome-shell[5417]: JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/utils.js 34]: reference to undefined property Symbol.toPrimitive
out 21 15:40:34 u gnome-shell[5417]: JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js 1361]: unreachable code after return statement
out 21 15:40:33 u gnome-shell[5417]: Some code accessed the property 'StatusNotifierWatcher' on the module 'interfaces'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
out 21 15:40:33 u gnome-shell[5417]: Some code accessed the property 'StatusNotifierWatcher' on the module 'statusNotifierWatcher'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
out 21 15:40:33 u gnome-shell[5417]: Some code accessed the property 'WORKAROUND_RELOAD_TYPE_REGISTER' on the module 'util'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
out 21 15:40:33 u gnome-shell[5417]: Some code accessed the property 'DBusMenu' on the module 'interfaces'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
out 21 15:40:33 u gnome-shell[5417]: JS WARNING: [resource:///org/gnome/gjs/modules/tweener/tweener.js 540]: reference to undefined property "isSpecialProperty"
out 21 15:40:33 u gnome-shell[5417]: Telepathy is not available, chat integration will be disabled.
out 21 15:40:33 u gnome-shell[5417]: JS WARNING: [resource:///org/gnome/shell/ui/slider.js 38]: reference to undefined property "CallyActor"
out 21 15:40:33 u org.gnome.Shell.desktop[5417]: current session already has an ibus-daemon.
out 21 15:40:32 u gnome-shell[5417]: JS WARNING: [resource:///org/gnome/shell/ui/osdMonitorLabeler.js 59]: reference to undefined property "MetaDBusDisplayConfigSkeleton"
out 21 15:40:32 u gnome-shell[5417]: JS WARNING: [resource:///org/gnome/shell/ui/layout.js 217]: reference to undefined property "MetaWindowGroup"
out 21 15:40:32 u gnome-shell[5417]: JS WARNING: [resource:///org/gnome/shell/ui/main.js 315]: reference to undefined property "MetaStage"
out 21 15:40:31 u org.gnome.Shell.desktop[5417]: Window manager warning: CurrentTime used to choose focus window; focus window may not be correct.
```

**Comment by zagortenay333** [comment]
I don't see any errors there regarding this extension.

**Comment by zagortenay333** [comment]
Any success?

**Comment by zagortenay333** [comment]
Closing as usual due to inactivity.

**Comment by he7d3r** [comment]
No success. If I keep a copy of this extension in the folder
> ~/.local/share/gnome-shell/extensions/timepp@zagortenay333

I am not able to log in using a graphical interface.

**Comment by zagortenay333** [comment]
Did you try the latest version from github? I can't reproduce this without any info.

**Comment by he7d3r** [comment]
Yes. I did clone it from github and after I pressed `ALT+F2` and `r` I was not able to use the desktop anymore (even after rebooting). The only way I was able to use the computer again was after I used CTRL+ALT+F5 to login using the console and moved the folder outside of `~/.local/share/gnome-shell/extensions`.

**Comment by zagortenay333** [comment]
When the desktop crashes go to a tty (ctrl-alt-f5) and then run:
```
journalctl /usr/bin/gnome-shell -r
```
Search for 'timepp'.
In case you don't know, you will get the `less` program. `q` to quit it and `/` to search stuff. Press `n` repeatedly to go through everything that was found.

**Comment by he7d3r** [comment]
The pattern is not found

**Comment by zagortenay333** [comment]
Gosh. Ok, write the output into a file and put it on [pastebin](https://pastebin.com/) or something. Again in a tty:
```
journalctl /usr/bin/gnome-shell -r > ~/Documents/timepp_log.txt
```
Maybe there is something else in there; otherwise, I'm out of ideas :cry:

**Comment by he7d3r** [comment]
https://dpaste.dzfl.pl/1e998782737f

**Comment by zagortenay333** [comment]
Nothing in there pointing to this extension... Are you on wayland, btw? Maybe try xorg.

Other than that, the only thing you can do is to try and debug it yourself. You can try to disable all section modules and start enabling them one after the other to try to maybe narrow down the culprit.

To disable the modules, go to the `extension.js` file and comment out the lines:
https://github.com/zagortenay333/timepp__gnome/blob/1b07261f9a7443b133da8aa5118d3bc99a5f716b/extension.js#L19-L24
https://github.com/zagortenay333/timepp__gnome/blob/1b07261f9a7443b133da8aa5118d3bc99a5f716b/extension.js#L162-L176
https://github.com/zagortenay333/timepp__gnome/blob/1b07261f9a7443b133da8aa5118d3bc99a5f716b/extension.js#L111-L135
And for the pomodoro section don't forget to comment this out:
https://github.com/zagortenay333/timepp__gnome/blob/1b07261f9a7443b133da8aa5118d3bc99a5f716b/extension.js#L202-L204

If disabling all sections still crashes it, then the issues is with something in the `extension.js` file. You could try to disable chunks of code carefully 'till you can narrow it down.

**Comment by zagortenay333** [comment]
One other potential culprit could be the custom theme funcs. You could try to comment out that:
https://github.com/zagortenay333/timepp__gnome/blob/1b07261f9a7443b133da8aa5118d3bc99a5f716b/extension.js#L156
And:
https://github.com/zagortenay333/timepp__gnome/blob/1b07261f9a7443b133da8aa5118d3bc99a5f716b/extension.js#L177-L180

**Comment by he7d3r** [comment]
After commenting out the lines mentioned on https://github.com/zagortenay333/timepp__gnome/issues/26#issuecomment-341074045, I was able to restart gnome-shell without freezing the system.

It still worked after I restored the lines related to context menu, timer, stopwatch, pomodoro and alarms.

However, restoring the 5 lines related to "todo" crashes it again.

BTW: I believe I'm using xorg, given this:
> $ echo $XDG_SESSION_TYPE
> x11

**Comment by zagortenay333** [comment]
Ok, we got some progress here :smile: So the culprit is somewhere in the todo section..

Do the same with these lines respectively (comment them out):
https://github.com/zagortenay333/timepp__gnome/blob/8823e1d44f675c932a4453a63e7f51c8f04afa25/sections/todo/MAIN.js#L520
And:
https://github.com/zagortenay333/timepp__gnome/blob/8823e1d44f675c932a4453a63e7f51c8f04afa25/sections/todo/MAIN.js#L518

**Comment by he7d3r** [comment]
I uncommented the 5 lines related to "todo", and commented the two above, and I was able to restart gnome-shell just fine.

**Comment by zagortenay333** [comment]
Comment the 2 lines above individually; we gotta narrow it down.

**Comment by he7d3r** [comment]
It does **not** crash if I use
```javascript
this.stats_view = new VIEW_STATS.StatsView(this.ext, this, 0); 
// this._init_todo_file();
```
It crashes if I use
```javascript
// this.stats_view = new VIEW_STATS.StatsView(this.ext, this, 0); 
this._init_todo_file();
```

**Comment by zagortenay333** [comment]
Ok, now try commenting out this:
https://github.com/zagortenay333/timepp__gnome/blob/8823e1d44f675c932a4453a63e7f51c8f04afa25/sections/todo/MAIN.js#L619-L623

**Comment by zagortenay333** [comment]
If that doesn't work, try:
https://github.com/zagortenay333/timepp__gnome/blob/8823e1d44f675c932a4453a63e7f51c8f04afa25/sections/todo/MAIN.js#L563-L581

**Comment by he7d3r** [comment]
It didn't crash when I commented out lines 619-623 (and restored line 520).

**Comment by zagortenay333** [comment]
Aha, comment out these lines individually:
https://github.com/zagortenay333/timepp__gnome/blob/8823e1d44f675c932a4453a63e7f51c8f04afa25/sections/todo/MAIN.js#L620-L622

**Comment by he7d3r** [comment]
It crashed in the three cases =/ so I commented out the whole block again for now.

**Comment by zagortenay333** [comment]
Sorry for bothering you, but we are getting somewhere. Comment this line out:
https://github.com/zagortenay333/timepp__gnome/blob/8823e1d44f675c932a4453a63e7f51c8f04afa25/sections/todo/MAIN.js#L789

**Comment by he7d3r** [comment]
After I uncommented lines 619-623, and commented 789, it crashed.

**Comment by zagortenay333** [comment]
Could you comment this out:
https://github.com/zagortenay333/timepp__gnome/blob/8823e1d44f675c932a4453a63e7f51c8f04afa25/sections/todo/MAIN.js#L803-L805

Also, have you ever been able to use this extension? The reason I'm asking is that the function `create_tasks` shouldn't have been called at all if you didn't select a todo file in the settings.

**Comment by he7d3r** [comment]
I think I was able to see the menus the first time I installed it, and while checking its configuration options I probably tried to select my old todo file. But at some point it crashed and I was never able to see the todo list. Then I tried to remove the extension from the folder, so that I could use the computer again.

Now that you mentioned it, I checked at gnome-tweaks tool and was able to set the todo and done files to empty files, and to uncomment all lines from the tests above, and it loaded just fine :-)

Maybe the syntax used in the todo/done files was the culprit? (it was a file created by the extension [todotxt](https://extensions.gnome.org/extension/570/todotxt/))

**Comment by zagortenay333** [comment]
Hmm, do you remember at which point it crashed? Did you manage to press the add button?

**Comment by he7d3r** [comment]
I'm not sure. At the first time it might have been when I closed the window I was using to choose the todo file.

Which add button? The [+] icon in the list of todo files of the gnome-tweaks? Or the "+ Add new task" in the menu?

**Comment by zagortenay333** [comment]
Srry, I meant the Ok button when you were selecting the todo file.

**Comment by zagortenay333** [comment]
Also, just to make it clear, are you able to load the files that you wanted to load?

**Comment by he7d3r** [comment]
So, I was able to create an empty todo.txt file, and load it into the extension, and it seems the "+ Add new task" is also working.

After that I started copying the items from my old todo.txt to the new one, line by line, and saving the file after each new line. When I copied a line like the following, the desktop become unresponsive:
```
(B) Test (see: http://example.com/ccccccc/eeeeeeee/123456) +foo +bar
```

**Comment by zagortenay333** [comment]
Nice! I finally figured what it is.

The url regex I was using was faulty and caused an infinite loop/recursion: https://regex101.com/r/swxUfd/1.
I updated to a better one now: https://gist.github.com/dperini/729294

Thanks for you help! :smile:

**Comment by zagortenay333** [comment]
I could swear I was using the regex from dperini to begin with, no clue where the faulty regex came from... :confused:

**Comment by he7d3r** [comment]
Great!

**Comment by zagortenay333** [comment]
Btw, timepp will make the url clickable, so make sure to add a space between the parentheses and the url.
