### ISSUE TITLE
Sort by threshold date

### ISSUE THREAD

**Issue by smichel17** [zagortenay333/cronomix#27]
For the purposes of sorting by threshold, if a task does not have a threshold date, fall back to using its creation date.

I have found this to be the most useful sort (older threshold -> lower on the list), as it's a form of pseudo-priority (stuff that you've passed the threshold for or added to your list most recently is likely to be at the front of your mind).

An alternative implementation would be to add a toggle to use threshold date as creation date if one exists.

**Comment by zagortenay333** [comment]
Don't understand this? How is the creation date supposed to be used as the threshold if it is the same date you created the task on? A threshold date is in the future.

**Comment by smichel17** [comment]
I updated the issue, does that make more sense?

**Comment by zagortenay333** [comment]
Actually, no.
There is no such thing as sorting by threshold date here. Threshold tasks are hidden until the threshold date is reached. If you want to see them, you flip that toggle in the filters view or use the search view.

**Comment by smichel17** [comment]
Say I added 5 tasks last week with different threshold dates:

```
2017-10-20 A t:2017-10-26
2017-10-21 B t:2017-10-24
2017-10-22 C t:2017-11-25
2017-10-23 D
2017-10-23 E t:2017-11-01
```
`E`'s threshold has not passed yet, so it will not be shown. `A`, `B`, and `C` will be shown because the threshold has been passed, but the threshold does still exist in the task, and can be useful to sort by. 

I'd prefer to have them appear in this order, which corresponds to the dates they appeared in my list (most recent first):

```
2017-10-20 A t:2017-10-26
2017-10-22 C t:2017-11-25
2017-10-21 B t:2017-10-24
2017-10-23 D
```

**Comment by zagortenay333** [comment]
Oh. Actually, when the threshold date is reached I remove that extension from your todo.txt file. It seemed like the natural thing to do. I could also keep it in there, but I don't see the benefit.

Is it really that useful to you?

**Comment by smichel17** [comment]
Yes, very! It's how I sort my inbox and the 3rd criteria I use to sort my tasks (after priority and due date).

**Comment by smichel17** [comment]
It's also useful with recurring tasks. Say I have a task
```
2017-10-10 A t:2017-10-20 due:2017-10-21 rec:+5d
```
(note: `+5d` is [Simpletask](https://github.com/mpcjanssen/simpletask-android)'s equivalent of Time++'s `x-5d`)

Say I complete the task on the 21st; the recurring version will have `t:2017-10-25 due:2017-10-26`.

I use this for chores like laundry/vacuuming, and some shopping list items.

**Comment by zagortenay333** [comment]
What about this:
There will be no option `sort by threshold date`, but anytime a task has a threshold date it's creation date will be set to the threshold date? That way sorting by creation date includes the threshold date.

**Comment by zagortenay333** [comment]
Above comment edited. Meant to say there will be **no** option `sort by threshold date`.

**Comment by zagortenay333** [comment]
I pushed that I idea now. Tell me what you think about it.

So there is no `sort by threshold date` option, but if a task has a threshold date, then it's creation date will be made equal to it's threshold date.

Also, the threshold date extension is now kept in the todo.txt file.

**Comment by zagortenay333** [comment]
Btw, whoever came up with the name _threshold_? This extension should have been called _defer_...

**Comment by smichel17** [comment]
Works nicely for me, thank you very much!

I originally asked for the option because I suspect in the future there will be someone who wants to sort by creation date without considering threshold dates. However, in retrospect I suppose that is premature optimization; better to wait and see if that is actually a problem than add a useless option.

> Btw, whoever came up with the name threshold? This extension should have been called defer...

Not sure, although I suspect [this](https://github.com/todotxt/todo.txt-cli/wiki/Todo.sh-Add-on-Directory#future-tasks) was the first place they were used.

**Comment by zagortenay333** [comment]
Glad it works for you.

I changed to _defer_. You can now use `t:date` or `defer:date`. The word _defer_ will be used throughout the extension instead of _threshold_.
