### ISSUE TITLE
Alarm Sound Dropdown Never Saves Selected Option | Ubuntu 17.10

### ISSUE THREAD

**Issue by Munk3y** [zagortenay333/cronomix#28]
I haven't tried to reproduce this on other distributions but in Ubuntu 17.10 x64, I cannot seem to select and save a different sound for the Alarm than "beeps.ogg".

**Reproduction:**
![alarmsound](https://user-images.githubusercontent.com/3118915/32325229-7f09fb24-bfa4-11e7-831d-9aba9d303ed6.png)

-Right click on Extension in top bar and select: Open Settings
-Select the Alarms tab
-Select a different Alarm Sound
-Note no Save button or any other button than the "X" (Close button) on the top right
-Click Close Button
-Repeat navigation to Alarm Sound area and note, it's now set back to "beeps.ogg"

**Comment by zagortenay333** [comment]
Fixed.

**Comment by zagortenay333** [comment]
Let me know whether it works.

**Comment by Munk3y** [comment]
Apologies for the slow response. I have just checked and confirmed that it is fixed! Great job, thanks for the quick fix.
