### ISSUE TITLE
Repeat notification sound until user acts on

### ISSUE THREAD

**Issue by anupam207** [zagortenay333/cronomix#3]
An option to repeat the notification sound for alarm/countdown until user stops it manually will be useful.

**Comment by zagortenay333** [comment]
I think it's doable.

**Comment by zagortenay333** [comment]
It looks like it can't be done cleanly.

There might be one crappy way of doing it, but it would require the user to install dependencies, which I don't want to do.

Closing for now.

**Comment by zagortenay333** [comment]
Gonna keep this open. Maybe someone figures it out.

**Comment by zagortenay333** [comment]
test

**Comment by zagortenay333** [comment]
@anupam207 This is now working! Thanks to the @felipeborges and the focusli extension.

**Comment by zagortenay333** [comment]
I also fixed the no repeat issue the focusli extension has: https://github.com/felipeborges/gnome-shell-extension-focusli/issues/12
