### ISSUE TITLE
Dropdown menu only appears when clicked.

### ISSUE THREAD

**Issue by Vaesper** [zagortenay333/cronomix#31]
Most system tray items that have a dropdown menu show it whenever the mouse rolls over them while any other dropdown menu is open. Time++ only shows it when you actively click on it.

To see the issue in action:
1. Open the Time++ dropdown menu.
2. Mouseover to the network/sound/power default system tray item.
3. The dropdown menu of this item appears.
4. Mouseover back to Time++
5. The dropdown menu of Time++ doesn't (re)appear.

**Comment by zagortenay333** [comment]
Should be fixed now. Let me know if it works.
