### ISSUE TITLE
Cannot open settings in GNOME 3.26

### ISSUE THREAD

**Issue by OriginCode** [zagortenay333/cronomix#35]
Error Messages:
 
     GLib.ConvertError: The URI “” is not an absolute URI using the “file” scheme

    Stack trace:
      Settings<._bind_settings@/home/origincode/.local/share/gnome-
    shell/extensions/timepp@zagortenay333/prefs.js:343:33
      wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
      Settings<._init@/home/origincode/.local/share/gnome-
    shell/extensions/timepp@zagortenay333/prefs.js:48:9
      wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
      _Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
      Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
      buildPrefsWidget@/home/origincode/.local/share/gnome-
    shell/extensions/timepp@zagortenay333/prefs.js:776:20
      Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
      wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
      Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
      wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
      main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
      @<main>:1:43

**Comment by zagortenay333** [comment]
This is fixed in the github version. The gnome-extensions site is waiting on review.
