### ISSUE TITLE
Error on init (Gnome 3.26.2)

### ISSUE THREAD

**Issue by Cybolic** [zagortenay333/cronomix#39]
When installing the extension from Github, the extension fails to load with the following message in Looking Glass: `TypeError: this.daily_csv_file is null`.
I had briefly installed the extension through the Gnome Extensions website before removing it and installing this one (since the preferences dialogue wouldn't open on that version - I believe the error was `"" is not a URL` ) just in case that might have caused the error.

**Comment by zagortenay333** [comment]
Should be fixed now. Let me know if it works.

**Comment by Cybolic** [comment]
It seems to work, yes.
I had got it running anyway be setting the todo.txt csv directory in the preferences dialogue, but removing that todo.txt definition and adding a new one (with a different name to make sure) and not selecting any csv directory still functions, so my guess is that it's fixed.

**Comment by zagortenay333** [comment]
It was just a silly bug that happened when you didn't choose a csv dir in the preferences. :smile:

**Comment by Cybolic** [comment]
Actually it happened before I ever opened the preferences, but yeah, it was definitely a minor bug :)
