### ISSUE TITLE
Extension shows error after locking and unlocking screen

### ISSUE THREAD

**Issue by anupam207** [zagortenay333/cronomix#4]
My system: Ubuntu GNOME 17.04, GNOME Shell version 3.24.2
Steps to reproduce:
1. Lock the screen. Notice that the extension icon is visible on the password screen (no other extension icon is visible).
2. Unlock the screen.
3. Extension shows error (see screenshots). Timer and stopwatch sections stop working too.

![screenshot from 2017-06-23 17-49-25](https://user-images.githubusercontent.com/20688749/27482055-6a96b052-583d-11e7-8bdc-0976bf93c17e.png)
![screenshot from 2017-06-23 17-48-36](https://user-images.githubusercontent.com/20688749/27482056-6b5b78c4-583d-11e7-8027-b4987aff8f49.png)

**Comment by zagortenay333** [comment]
See if there is any errors in the journalctl.
Run
```
journalctl /usr/bin/gnome-shell -r  | less
```
And see if there are any errors related to timepp. The `less` prog lets you search with `/` . `q` to exit.

**Comment by anupam207** [comment]
I found this:
`Extension "timepp@zagortenay333" had error: TypeError: this.cache_file is null`

**Comment by zagortenay333** [comment]
Can you see what file and line?

**Comment by yyyyuuu** [comment]
I also met for this problem

**Comment by zagortenay333** [comment]
Can you paste the output of journalctl -r to pastebin or something?

**Comment by zagortenay333** [comment]
Also, can you try the version from github to see if the error is there?

**Comment by anupam207** [comment]
Here's the output of `journalctl -r`:
[journalctl.txt](https://github.com/zagortenay333/timepp__gnome/files/1097990/journalctl.txt)

Also I tried the version from github, the issue is still present. Milliseconds feature in stopwatch works fine though 👍

**Comment by zagortenay333** [comment]
Do you have the cache directory under `~/.cache/timepp_gnome_shell_extension` ?

**Comment by zagortenay333** [comment]
I can't replicate this btw.

**Comment by anupam207** [comment]
Yes, I do have the directory.
![screenshot from 2017-06-23 19-38-07](https://user-images.githubusercontent.com/20688749/27485757-a6bb64de-584b-11e7-92d0-8ca451ac2999.png)

**Comment by zagortenay333** [comment]
So, you get this error only after you locked the screen?

**Comment by zagortenay333** [comment]
Also, when you restart the shell, does the same error persist?

**Comment by anupam207** [comment]
Same thing happens after waking up and unlocking after suspend too. Restarting GNOME shell fixes this.

**Comment by zagortenay333** [comment]
Could you please download the extension from this branch: https://github.com/zagortenay333/timepp__gnome/tree/bug_fix

First uninstall the extension, delete the cache file, restart shell, and then install from this branch.

**Comment by anupam207** [comment]
As I mentioned before the Time++ icon on top panel is visible on the lock screen. But there also the timer and stopwatch don't work. Could you make the icon not appear on the lock screen? This is also a mild privacy issue as my tasks are accessible even when the screen is locked.

**Comment by zagortenay333** [comment]
Shell disables all extensions when you go to lock screen. Since there is a bug, it fails.

I managed to finally replicate the bug. You disabled one of the sections, right?

**Comment by anupam207** [comment]
yes! pomodoro. sorry i forgot to mention that before

**Comment by zagortenay333** [comment]
OK, could you try the version from the master branch again. I think it's fixed now.

**Comment by anupam207** [comment]
Yes, it's working alright  now! 👍 💯

**Comment by zagortenay333** [comment]
Nice.
