### ISSUE TITLE
Can't open settings

### ISSUE THREAD

**Issue by dac73** [zagortenay333/cronomix#40]
GLib.ConvertError: The URI “” is not an absolute URI using the “file” scheme

Stack trace:
  Settings<._bind_settings@/home/dario/.local/share/gnome-shell/extensions/timepp@zagortenay333/prefs.js:343:33
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Settings<._init@/home/dario/.local/share/gnome-shell/extensions/timepp@zagortenay333/prefs.js:48:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
  Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/_legacy.js:117:20
  buildPrefsWidget@/home/dario/.local/share/gnome-shell/extensions/timepp@zagortenay333/prefs.js:776:20
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:91:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:246:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:402:5
  @<main>:1:43

**Comment by zagortenay333** [comment]
Please read existing open/closed issues before opening a new one. This is already fixed in the github version.

**Comment by dac73** [comment]
Sorry, just saw that (after opening ticket :()

**Comment by zagortenay333** [comment]
No problem :smile:
