### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by DevilishSpirits** [zagortenay333/cronomix#45]
Good morning. I have do a french translation of your Time++, here's the po file.
[fr.po.gz](https://github.com/zagortenay333/timepp__gnome/files/1616382/fr.po.gz)

I have tried to adapt it as much better, then some translations have a little different sense, for sample time tracker is translated to "traqueur d'activité" ("activity tracker") instead of "traqueur de temps" (I'm not fully sure of this translation...)

**Comment by zagortenay333** [comment]
Thx. I added them.

Yeah, time-tracker == activity-tracker.
