### ISSUE TITLE
stop watch changes time after locking and unlocking the system

### ISSUE THREAD

**Issue by fel5** [zagortenay333/cronomix#48]
System: Fedora 27, Gnome 3.26.2

Sometimes if i use the stop watch, stop it, lock the system and then unlock it again, the stop watch is at a completely different time. For example if the stop watch is at 1 h, after i lock and unlock the system the stop watch could be at 14 h.

**Comment by zagortenay333** [comment]
This should be fixed now. Let me know if it works correctly.
