### ISSUE TITLE
Tags from hidden tasks not available in autocompletion

### ISSUE THREAD

**Issue by Vaesper** [zagortenay333/cronomix#49]
Try adding some task with description "+test123 @test456 this is just a test", you will see the test123 project and the test456 contexts appear in autocompletion. Then add "h:1" to the end of said task; they will no longer appear.

**Comment by zagortenay333** [comment]
Are you sure you are using the latest version from github? I remember I fixed this bug. The gnome extension site hasn't been updated in an eternity.

**Comment by Vaesper** [comment]
I am using the e.g.o version. Any chance that will be updated?

**Comment by zagortenay333** [comment]
It's not up to me. I always submit to that site but the reviewers are volunteers so... You can track the review queue here: https://extensions.gnome.org/review/

This bug is solved in the github version  so I'm gonna close it.
