### ISSUE TITLE
Standalone version?

### ISSUE THREAD

**Issue by gsantner** [zagortenay333/cronomix#50]
Hi there,

I really enjoy your extension. Are there any plans for making a standalone applicatio out of it - to make it useable on any DE? It's quite massive and feature packed therefore asking.

**Comment by zagortenay333** [comment]
Hi.

Nope, no plans on my part on making it a standalone app.

**Comment by davidak** [comment]
@gsantner maybe you like https://github.com/sanpii/effitask?

**Comment by gsantner** [comment]
Thanks for the link!

I've developed an application on my own, pretty popular actually :D.  <https://gsantner.net/project/markor.html>

**Comment by davidak** [comment]
Cool. I actually use it on Android!
But i'm also happy to found a nice GUI desktop client.

**Comment by gsantner** [comment]
There use todotxt-machine with big font-size and scale

**Comment by davidak** [comment]
I prefer a GUI over TUI or CLI. But it looks good. I considered to package it also for NixOS, but the last release is 5 years ago. So it seems unmaintained :(
