### ISSUE TITLE
request: number in status menu only for filtered items

### ISSUE THREAD

**Issue by nielsk** [zagortenay333/cronomix#51]
Hi,

would it be possible that the number in the status menu shows only the number of items the current filter presents? So that when I have a long todo.txt and filter it down to only priorotized items, that the number in the status menu would show only the number of prioritized items.
Thanks.

**Comment by zagortenay333** [comment]
Yeah, that's trivial to implement. It's just that I have to add another option for it, and adding more and more options for special cases clutters everything. Hmm...

**Comment by zagortenay333** [comment]
I think adding that option to the filter view would make sense. Some toggle like `panel item counter respects filter` or something like that.

**Comment by nielsk** [comment]
That would be great. Thanks :)

**Comment by zagortenay333** [comment]
Sorry, not gonna implement this. There is some awkwardness with idle loading tasks for performance reasons that would make this option clunky.
