### ISSUE TITLE
request: filter on due-date

### ISSUE THREAD

**Issue by nielsk** [zagortenay333/cronomix#52]
Hi,
it would be nice to have a filter for due-dates (like "due today", "items with a due-date").
Thanks

**Comment by zagortenay333** [comment]
I don't really want to add a special feature for that because you can make custom filters in the filter menu; they should work pretty well. Add a filter like `due:20--`.

**Comment by nielsk** [comment]
Thanks. I completely missed that function m(
Sorry for wasting your time
