### ISSUE TITLE
Custom presets for Timer

### ISSUE THREAD

**Issue by tekvsakdan** [zagortenay333/cronomix#53]
Is it possible to implement custom presets for Timer?

For example:
- Cooking, 10 min
- Break, 15 min
- Studying, 45 min

**Comment by zagortenay333** [comment]
This is now implemented. Let me know if works well!

**Comment by zagortenay333** [comment]
The way it works is that there is always a default preset which cannot be deleted. This preset is the one you activate when you use the sliders.
![screenshot from 2018-02-23 19-18-05](https://user-images.githubusercontent.com/11144630/36609797-684e0352-18ce-11e8-8c24-6091cc01fa9c.png)

**Comment by tekvsakdan** [comment]
Thanks. It is working as expected \o/
