### ISSUE TITLE
request: Recurrence tasks.

### ISSUE THREAD

**Issue by BeforeFlight** [zagortenay333/cronomix#54]
This option would be very useful. For example one may add tasks 'train with Anki', 'walk out the dog', 'play the piano', 'read news', 'call to mom', 'visit dentist', 'prepare gifts for New Year' etc, and mark them with **recurrence**. 

I mean there are a lot of every day (week-month-years-..) todos that one must keep in mind. So would be great to have tracking of all of these staff. And if one can track, for example birthdays, in calendar apps, it is not handy to track there every-day things for sure.

**Comment by zagortenay333** [comment]
T_T

https://github.com/zagortenay333/timepp__gnome#todotxt-extensions

**Comment by BeforeFlight** [comment]
Ooops. Sorry about that :|

**Comment by zagortenay333** [comment]
lol No problem. The README is pretty huge so it's easy to miss.

**Comment by BeforeFlight** [comment]
In fact i missed it because read syntax manual with _syntax link_ provided when create new record, which led to todo.txt repo (as i now see..) where no extensions records. But didn't read your own readme. So sorry again - really awkward.

By the way thanks a lot - extension is in **top 5** among all of them for Gnome (cannot range those 5 because it's all simply different by features). And if i didn't say it before - it's just because it's obvious. For everyone :)

**Comment by BeforeFlight** [comment]
And another one question - sorting with recurrence tag? Or it's already there as well?)

**Comment by zagortenay333** [comment]
Actually, I updated that syntax link recently. It now points to: https://github.com/zagortenay333/timepp__gnome#todotxt-syntax  
You're probably using the version of the extension from the extensions site which is ancient by now.

There is no explicit sorting by recurrence because I didn't think it was needed. I might add in.

**Comment by BeforeFlight** [comment]
> I didn't think it was needed. I might add in.


It's really not crucial option (for example one may use separate file for recurrence todos). But if using one file (it's just 'cleaner' - no need to maintain another file, and switch between them) there are some reasons for such filter. In my case i prefer to finish every-day-recurrence tasks first (train with anki, read news, etc) in order to stop thinking about 'small' things and concentrate on main work later.

As for old extension version - again it's my bad. I'm new at ubuntu and thought that gnome extensions are mirrored with github repos (cause all off them have links to github in description), so one don't need to track every single (of 30-40..it's really strange why it's not just mirroring?) repos for updates. But as you say it's not like that. So i have to go dig some general info about extensions. And will update from you repo for sure.

**Comment by zagortenay333** [comment]
Just to be clear here.  
Closed recurrence tasks are not visible; you need to flip that toggle in the filters view or start searching. So they are out of the way. When I say sorting recurring tasks, I mean sorting open recurring tasks by how much time until they recur again (which might be useful.)

Yeah, they don't mirror. Extensions are sitting in a review queue, but the reviewers are volunteers so it takes a lot of time to approve them..

**Comment by BeforeFlight** [comment]
I meant another type of  sort - first the recurring tasks (open of course) then not recurring. 
But your type might be useful as well. For example - recurring tomorrow i must do first and only after may do the next week ones, such sort will be native.

**Comment by zagortenay333** [comment]
@BeforeFlight Just to let you know that you can sort by recurrence date now.

**Comment by BeforeFlight** [comment]
Thank you. It is work as expected.
