### ISSUE TITLE
Request: Time tracker idle detection

### ISSUE THREAD

**Issue by hackel** [zagortenay333/cronomix#55]
One feature I really miss from other time trackers I've used is idle detection.  When it detects that you haven't been using your computer for a user-specified length of time, it pops up a dialogue asking you what to do.  You can either:
1. revert the timer to when you went idle, and stop the timer.
2. revert the timer to when you went idle, and start the timer.
3. continue the timer.

Of course this would require a resolution to #5 to be terribly useful, as well as recording explicit start/stop times for each interval.

**Comment by zagortenay333** [comment]
Although I implemented the intervals stuff already (haven't pushed yet) I won't implement this since I don't need it. 
People are free to make a pull request if it doesn't complicate the code base too much.

**Comment by zagortenay333** [comment]
Btw, you can prevent the tracker from running when idle by simply letting the screen lock. This will stop the tracker.
