### ISSUE TITLE
[request] monochrome option

### ISSUE THREAD

**Issue by ghost** [zagortenay333/cronomix#57]
Hello, thank you for this extension, a must have!

I would like to know if it would be possible to add a setting for people who don't want any color. For example the green todo when you have 0 tasks, stuff like this.

**Comment by zagortenay333** [comment]
Not gonna add any monochrome option, although I might remove that green indicator when there are no tasks. It's probably annoying and I haven't seen it in a while cause I always have some long-running tasks.

**Comment by zagortenay333** [comment]
Btw colors and stuff is all defined in css, so you can edit it yourself any way you want. For example, the green todo panel item is defined here: https://github.com/zagortenay333/timepp__gnome/blob/4a7847e19a176de11bf46b0502c99c176d2e0c5b/stylesheet.css#L36-L39

**Comment by ghost** [comment]
Yeah, thanks :) It's what I did, but I always prefer an officialy integrated solution.
