### ISSUE TITLE
Sync with GNOME apps?

### ISSUE THREAD

**Issue by ghost** [zagortenay333/cronomix#58]
Hello, would it be technically possible to sync with related GNOME apps?

I mean, for example setting an alarm in this extension could add an alarm to GNOME Clocks and vice-versa. GNOME Clocks has alarm, stopwatch, and timer, IMO this extension would be more useful and helpful if it was a way to access GNOME Clocks features from the panel instead of a separate tool that does the same thing and gives an impression of wanting to reinvent the wheel _(I know it's not your goal, and it's not what I think, but it's just what some people could have in their mind using this)_.

**Comment by zagortenay333** [comment]
Not gonna do this.
