### ISSUE TITLE
activating this extension is changing my locale language gnomeshell settings

### ISSUE THREAD

**Issue by vlag24** [zagortenay333/cronomix#6]
Hello,
I love your extension but when I activate it, my locale language settings in gnome is changing to English (I'm French) not a big deal but... look at the top right
![capture d ecran de 2017-07-08 18-09-22](https://user-images.githubusercontent.com/6505894/27987104-1973f96e-6409-11e7-960d-24e44e540c77.png)
![capture d ecran de 2017-07-08 18-09-58](https://user-images.githubusercontent.com/6505894/27987109-256db67e-6409-11e7-82d6-4acd0b212971.png)

regards

**Comment by zagortenay333** [comment]
That's weird.

Does it update immediately, or do you have to restart first?

**Comment by zagortenay333** [comment]
Also, are you using the version from github?

**Comment by vlag24** [comment]
I forgot to tell you it accurs when I restart or when I do a alt + f2 + r
I'm using the gnomeshell extension website version

**Comment by zagortenay333** [comment]
Please try the one from github and see if the bug is still there. The github version is way ahead of the other one.

**Comment by vlag24** [comment]
ok thanks, to be continued ;)

**Comment by zagortenay333** [comment]
If it still persist also check the output of :
```
journalctl /usr/bin/gnome-shell -r | less
```
You can use `/` to search for `timepp` or `time` and see if there are any bugs. `q` to quit.

**Comment by vlag24** [comment]
Well I did it but the problem is still here (I rebooted to be sure)
I've searched for my log and I found nothing related to timepp or time
My guess it should be an interaction with another extension, I have a lot (too much maybe)

**Comment by zagortenay333** [comment]
Disable all extensions except for this one to be sure that it really is this extension that causes it.

What I don't understand is how your locale can change at all if you didn't log out first. You just restart gnome-shell and it changes?

**Comment by vlag24** [comment]
ah wait I use the search function of the terminal now I used your method "/timepp" (I'm not a pro lol)
and found this... (I can't copy/paste so here is a screenshot)
![capture d ecran de 2017-07-08 19-10-46](https://user-images.githubusercontent.com/6505894/27987660-60859eea-6411-11e7-9fb3-e645f5ae3cce.png)

- What I don't understand is how your locale can change at all if you didn't log out first. You just restart gnome-shell and it changes?
> yes, just restarting gnome-shell did it

I will try to search, one by one, which one associated with yours, could create this problem and I will let you know, maybe not this evening, but soon

**Comment by zagortenay333** [comment]
I actually get that error from time to time as well, but I can't figure out what it is. Sometimes it happens when I logout and it goes away. I don't think it has anything to do with this bug.

**Comment by zagortenay333** [comment]
Do you get the bug from the screenshot consistently? Next time you logout and log back in  check to see if the same bug is there.

**Comment by vlag24** [comment]
No, this bug is not consistent, just sometimes...
I installed the last version of the extension, with no luck, same issue.
Like I thought it was an interaction with another of my activated extension, I tried to deactivate each of my extension (with a alt+F2+r between each) and nothing new...
I keep Time++ deactivated for now. I will try withthe eventual future updates...

**Comment by zagortenay333** [comment]
Would you mind getting rid of this line and then trying out again:
https://github.com/zagortenay333/timepp__gnome/blob/master/extension.js#L31

**Comment by vlag24** [comment]
Ah yesss!!!! you've just found the fix ! 
I comented the line 31, do a gnome-shell restart and even restart my laptop to be sure and it works
big thanks ! All is back to normal ;)

**Comment by zagortenay333** [comment]
Well, not really. If I don't have that enabled, then custom translations don't work on my machine. Will have to look more into it..

**Comment by vlag24** [comment]
sadly I'm not a coder I can't really help you. I hope you find a fix.
But If you need me for testing, no problem !

**Comment by zagortenay333** [comment]
Ok, this should be fixed now with 83dc51bbfca66458890c24f32a7e43d3f8993b25.

Could you download the latest version and double check it works correctly?

**Comment by vlag24** [comment]
hello, just done and yes, it fixes my issue, all is working correctly !
thanks for your hard work :)

**Comment by zagortenay333** [comment]
Cheers.
