### ISSUE TITLE
Interoperability with Dash to Panel

### ISSUE THREAD

**Issue by YarnSphere** [zagortenay333/cronomix#62]
Hi! First of all, thank you for this great extension! It looks and works great for me. 

I've noticed, however, some interoperability issues with [Dash to Panel](https://github.com/home-sweet-gnome/dash-to-panel).

Issues when the panel bar is positioned at the bottom:
* The todo.txt popup doesn't show at all (I assume it is trying to appear beneath the panel, but since the panel is at the bottom, nothing shows up):
![screenshot from 2018-05-12 00-31-38](https://user-images.githubusercontent.com/8314616/39949771-3796483c-557d-11e8-9f8b-71b03a219c29.png)
* Sometimes the arrows on timer-related popups show at the top of the popup instead of at the bottom (this is tricky to reproduce and happens sometimes after triggering the popup multiple times):
![screenshot from 2018-05-12 00-33-48](https://user-images.githubusercontent.com/8314616/39949787-57cb6c04-557d-11e8-8f32-2fc637fdc3ba.png)

Issue when the panel bar is positioned at the top:
* The todo.txt popup overflows to the bottom of the screen (I have intellihide enabled on the panel and my todo.txt file is large enough that a scrollbar is required to list all tasks; note that the bottom of the picture below is the bottom of the screen):
![screenshot from 2018-05-12 00-37-07](https://user-images.githubusercontent.com/8314616/39949847-d31dbace-557d-11e8-9631-0b98d49a8412.png)

I've tested this issues in the latest master branch. They seem to be caused by some manual positioning of the popup menus that you might be doing (I'm not sure about this, it's just my intuition). I have no idea if they are fixable without tying your code to Dash to Dock's or even if fixing them is something you'd be interested in; nevertheless, I thought that an issue listing some incompatibilities that I found may be nice to have. :)

Again, thank you very much for your work!

**Comment by zagortenay333** [comment]
I'm too lazy to add hacks for problems with other people's extensions..
If an extension messes with the panel which as a result messes with all popup menus, then it makes no sense for any particular popup menu to introduce a hack around it. It's up to the panel modifying extensions to prevent this.

For example, dash-to-dock prevents all popup menus from being shown when it's on the bottom. I actually opened an issue for this: https://github.com/home-sweet-gnome/dash-to-panel/issues/200

The popup arrow is also definitely the fault of dash-to-dock.

I might add a feature to specify a max-height in order to help you with the intellhide thing.

**Comment by YarnSphere** [comment]
Ah, I think I'd read about that issue a while ago, totally forgot about it! You're absolutely right, though, if it's not your fault I think it should never be fixed here. I assumed you were doing some calculations to position the menus correctly and as a result they'd show up off position. This because the behaviour didn't seem to occur with other extensions; turns out it's just because the menu is too big.

The popup arrow one is weird because I can't reproduce it with any other extension. Are you absolutely sure you're doing nothing that might cause it?

The max-height setting could be useful and I'd appreciate it since I actually use the panel at the top and the other issues don't really bother me, but can't you somehow figure out the panel's height and set it appropriately automatically? I'm not 100% sure it has to do with the intellihide. Without intellihide what happens to me is that the popup no longer overflows at the bottom, but it still misses the margin at the bottom. It might still be Dash to Panel's fault, however.

**Comment by zagortenay333** [comment]
The intellhide extension doesn't correctly handle the max height property that is set on popup's. I'll add the max height tweak eventually but only cause it makes sense to have such a feature anyway.
You can test that it doesn't work on other menus by creating a bunch of notifications and opening the calendar menu. You can use the `notify-send` command.

Not sure about that arrow thing. I am manipulating the arrow, but should work correctly. Maybe I'll into it some day. It would help if you could replicate it consistently.

**Comment by YarnSphere** [comment]
Yeah, I understood that it's Dash to Panel's fault that the popup won't show and I appreciate the `max-height`! Also, I'm not using any other "intellihide extension", Dash to Panel itself now implements it, so yeah, it might be their fault again.

I can consistently replicate the arrow thing by hovering in and out of the timer's icon a few times until it randomly shows up; it is consistent in how it randomly occurs. :)

**Comment by zagortenay333** [comment]
@nunocastromartins Just to let you know that in the latest version all of these are fixed. I didn't add the max height prop, but there should be no issues. You can put the dash-to-panel on the bottom as well.
