### ISSUE TITLE
How can I plug a pomo to a special task using tracker_id

### ISSUE THREAD

**Issue by fredmj** [zagortenay333/cronomix#63]
Hello,
I really enjoy this `gnome-shell` version of `todo.txt` time tracking application.
But I think there could be a really nice option
# Automaticaly plug a "pomo" to a task
I'd like to start running a task each time I start a *pomo*.
At the end of my pomo, the task is ended up and the task is marked as completed (x).
As I mark my tasks as daily recursive, they will appear next time.
I find it could be a nice way to proceed a daily chained tasks list.

Let's say I have this tasks :
>  2018-05-14 learn time_pp            due:1d tracker_id: LTPP
>  2018-05-14 learn todo-cli.txt        due:1d tracker_id: LTDC

_How can I say to 'pomo' : "run the next uncompleted task fomr task/timetracker and when you'll stop mark this task as completed" ?_
_Do I have to use the `todo-cli.sh` ?_

**Comment by zagortenay333** [comment]
This is not possible currently, but it's trivial to implement.

For example, what about having the ability to type multiple `tracker_id` in the pomo settings, and then it will simply loop with each completed pomo?

**Comment by fredmj** [comment]
@zagortenay333 sounds good, but how can I achieve that ?
Sorry but I'm not a javascript guy.
When you say:
> [...] type multiple `tracker_id` in the pomo settings [...]

Is it there ?
https://github.com/zagortenay333/timepp__gnome/blob/ee1697f3c0e884da4382feaf5010f649bf7b7b8e/sections/pomodoro.js#L762-L773

**Comment by zagortenay333** [comment]
I meant I can implement it trivially when I get around doing it.

**Comment by fredmj** [comment]
Ooh I didn' get that, sorry.
Sure It would be great! The perfect handy tool for training sessions.

Here the use case I imagine :
1.  I define 4 tasks : git, Kubernetes, hadoop, tensorflow
  > *  2018-05-16 do some git due:1d tracker_id: git
  > *  2018-05-16 learn how to scale up pods due:1d tracker_id: kubernetes
  > *  2018-05-16 learn how to launch yarn app due:1d tracker_id: hadoop
  > *  2018-05-16 get a look on tensorflow distributed due:1d tracker_id: TF
2.  I include them in a named pomodoro loop : `pomoloop_training_session_#1`
2.  I start a pomodoro session : New `pomoloop` : pomoloop_training_session_#1
3.  pomo display **task `git` running : mm:ss** (or It could be **"do some git" : mm:ss**) according to the minutes and seconds of my settings
4.  The time tracking is running the corresponding task during the pomo session.
4.  At the end of the pomo, the taks is completed and pomo display : **task _git_ ended. Have a break!**
5.  And so on with all the others included tasks

I could save several loops "Cloud session", "CI/CD session", "docker session", "python session", ...

What you think?

**Comment by zagortenay333** [comment]
Yeah, I might add pomodoro presets like in the timer. Then this particular feature could be implemented nicely with those.

However, I just rewrote and added some new features and feel like taking a break from writing anything big for timepp.

**Comment by zagortenay333** [comment]
I will at some point rewrite timepp completely as a standalone application so I don't intend to add any new features in the extension. Gonna close this.
