### ISSUE TITLE
Enter should add new task

### ISSUE THREAD

**Issue by rusins** [zagortenay333/cronomix#64]
Currently (in latest Github master version) pressing enter creates a newline in the task entry. Would be nice if either shift+enter was designated to creating a newline, and enter would add the entered task, or if ctrl+enter was designated to add the task. Thanks!

**Comment by zagortenay333** [comment]
Added. Let me know whether it works correctly.

**Comment by rusins** [comment]
Works well! Thank you! Of course, pressing enter twice really fast adds another empty task, but that's just Gnome being slow I guess :D

**Comment by zagortenay333** [comment]
The second time you hit enter you are already in the default view where the `Add Task` button is in focus. Maybe that is causing it to happen?

I just pushed a little commit. Can you see whether it helps?

**Comment by rusins** [comment]
Damn, that did fix it! Works like a charm! :)
