### ISSUE TITLE
[Feature request] Sort tasks alphabetically by their content

### ISSUE THREAD

**Issue by YarnSphere** [zagortenay333/cronomix#65]
Hi there, would you be willing to add a sorting criteria to sort tasks alphabetically by their "content"?

My scenario might be slightly unconventional but, among other things, I use Todo.txt to keep track of the shows I watch and at which episode I am for each show. I'd like my sorting to give priority to the name of the show instead of the task creation date, which I have no interest in. It would make it easier to find and edit the "content" (usually update the episode I'm at) of the show I'm looking for.

I.e., I'd like my sorting to be: `pin > completed > priority > due date > context > projects > ALPHABETIC > creation date > completion date > recurrence date` (I don't really use recurrence date).

I don't think this should be especially difficult to implement, so I'd be willing to give it a try if you agree.

Thank you very much for your work!

**Comment by zagortenay333** [comment]
Added. Let me know if it works correctly.

**Comment by YarnSphere** [comment]
Quick!

Seems to work for me! Thank you very much!
