### ISSUE TITLE
Shortcut to search tasks doesn't focus input search field when popup menu isn't showing

### ISSUE THREAD

**Issue by YarnSphere** [zagortenay333/cronomix#68]
Hi, again!

I recently set the keyboard shortcut to search tasks (the one that goes by the label "Open popup menu and search tasks").

When I use the keyboard shortcut (with the popup menu hidden), what seems to happen is that the popup menu appears with the search input focused; then the popup menu's height is updated (and, in my case, the menu becomes scrollable) which causes the search input to lose focus.

If I use the keyboard shortcut whilst the menu is already showing then the menu's height seems to update whilst keeping the search input focused.

This effectively means that I have to use the shortcut twice to be able to search immediately. :)

Once again, thank you for the amazing extension!

**Comment by zagortenay333** [comment]
Should be fixed now. Let me know if it works.

**Comment by YarnSphere** [comment]
You're the best!

The popup also seems to open more fluidly now.
Issue is fixed for me. Again, thank you very much for the time you put on this!

**Comment by zagortenay333** [comment]
Cheers.
