### ISSUE TITLE
Can't load todo.txt file if folder name has white spaces

### ISSUE THREAD

**Issue by pablitok** [zagortenay333/cronomix#7]
Hi, I was trying to configure the extension with a todo.txt file created by an android app that set its location to a folder named "Simple App". There was no error message, I can select it and in the extension settings everything seems ok, but in the top bar I cannot see my todo, just the "select todo file in settings" message.
A quick fix was to create a link with no spaces on it

**Comment by zagortenay333** [comment]
Oh, interesting. Will look into it.

**Comment by zagortenay333** [comment]
This is fixed with b1bdd0ceec71a999a9b8a09a693d91e509be16c0

Let me know if it works.
