### ISSUE TITLE
[Feature Request] Add panel mode for only showing text when active

### ISSUE THREAD

**Issue by vhfmag** [zagortenay333/cronomix#70]
I just found out that extension and I love it, thanks for it!

That said, it does take a lot of space of the top bar:
![top bar screenshot](https://user-images.githubusercontent.com/357835/43646528-82a24176-970b-11e8-97c4-ef52fe6323ff.png)

So I was wondering if you would agree on adding a new pane mode for only displaying the text on the top bar for the timer, the countdown and the pomodoro timer when they're active, freeing up some space when not in use.

If that's desirable, I would be pleased to work on a PR implementing it!

**Comment by zagortenay333** [comment]
I added this quickly. Let me know if it works well.

**Comment by vhfmag** [comment]
Works like a charm! Thanks a lot :)
