### ISSUE TITLE
Notifications are persistent

### ISSUE THREAD

**Issue by rikenshah** [zagortenay333/cronomix#71]
I am mostly using the Pomodoro timer, and what I observe is with every new cycle/break, there is a notification (as expected), however, I have to manually close the notification. Till that time it persists, unlike other notifications which immediately goes away. Is there a way to make Pomodoro notifications non-persistent?

**Comment by zagortenay333** [comment]
I changed the urgency to normal. Let me know if it works correctly.

**Comment by rikenshah** [comment]
Yes that worked.
