### ISSUE TITLE
Time++ causes instability in Gnome when unlocking screen

### ISSUE THREAD

**Issue by pabloi** [zagortenay333/cronomix#73]
I am getting instability from gnome when unlocking it. I am not 100% sure this is due to Time++, but disabling the extension seems to help.

The steps to reproduce are: install Time++, lock the screen, then unlock it. It doesn't always happen, but occasionally the process to unlock is very slow, and more often than not, it just freezes. Pressing Ctrl+Alt+F1 returns me to the welcome screen most times (although sometimes a reboot was necessary).

I am not sure what I can do to help debug this (please let me know), or even find out if Time++ is indeed the culprit here. 

I am using Ubuntu 18.04, gnome-shell (3.28.2-0ubuntu0.18.04.1)

**Comment by zagortenay333** [comment]
Type into a terminal:
```
journalctl /usr/bin/gnome-shell -r | less
```
See if there is any mention of time++. Also are you using the github version?

**Comment by pabloi** [comment]
I installed the extension from extensions.gnome.org
The command returns a very long list, including mentions to timepp. I do not think these are related to the unlock instability as the timestamps do not match. I'll keep an eye next time it freezes and report back.

Just in case, most of the timepp mentions are of the form:

> Aug 16 15:06:00 COMPUTERNAME gnome-shell[10259]: Object St.Button (0x55fba28f64f0), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
> Aug 16 15:06:00 COMPUTERNAME org.gnome.Shell.desktop[10259]: == Stack trace for context 0x55fb9c2954c0 ==
> Aug 16 15:06:00 COMPUTERNAME org.gnome.Shell.desktop[10259]: #4 0x55fb9c71fd70 i   /home/pablo/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:188 (0x7f0e97906780 @ 12)
> Aug 16 15:06:00 COMPUTERNAME org.gnome.Shell.desktop[10259]: #3 0x7ffed6f4e450 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f0ed1eb5de0 @ 71)
> Aug 16 15:06:00 COMPUTERNAME org.gnome.Shell.desktop[10259]: #2 0x7ffed6f4e390 b   /home/pablo/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:252 (0x7f0e97906ab0 @ 801)
> Aug 16 15:06:00 COMPUTERNAME org.gnome.Shell.desktop[10259]: #1 0x7ffed6f4e2b0 b   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f0ed1eb5de0 @ 71)
> Aug 16 15:06:00 COMPUTERNAME org.gnome.Shell.desktop[10259]: #0 0x7ffed6f4d480 b   /home/pablo/.local/share/gnome-shell/extensions/timepp@zagortenay333/sections/alarms.js:402 (0x7f0e9790c2b8 @ 80)
>

**Comment by zagortenay333** [comment]
That alarms error is weird. Do you have the alarms enabled? Do you get that error multiple times?

Btw, you can run `journalctl /usr/bin/gnome-shell -f -o cat` which continuously monitors the log file and then interact with timepp to see more precisely what action causes an error.

But please use the github version just in case I didn't already fix in the last few commits.

**Comment by zagortenay333** [comment]
@pabloi any news?

**Comment by pabloi** [comment]
Sorry, I've not had time to look into this. I just installed the GitHub
version and will keep you posted.

Pablo A. Iturralde

**Comment by luiandresgonzalez** [comment]
I was also having certain system instability, same OS version and same source (Gnome extensions).
I also had a screen freeze while looking at the stats screen.
@zagortenay333 here is the output of 

> journalctl /usr/bin/gnome-shell -r | less

```
Aug 30 00:56:27 lambda org.gnome.Shell.desktop[27454]: #9 0x7ffd414f3860 b   resource:///org/gnome/shell/ui/tweener.js:219 (0x7f3ca04cf780 @ 15)
Aug 30 00:56:27 lambda org.gnome.Shell.desktop[27454]: #8 0x7ffd414f37c0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7f3ca04b5de0 @ 71)
Aug 30 00:56:27 lambda org.gnome.Shell.desktop[27454]: #7 0x7ffd414f3760 b   resource:///org/gnome/shell/ui/tweener.js:244 (0x7f3ca04cf808 @ 159)
Aug 30 00:56:27 lambda org.gnome.Shell.desktop[27454]: #6 0x7ffd414f36b0 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7f3ca04d2230 @ 386)
Aug 30 00:56:27 lambda org.gnome.Shell.desktop[27454]: #5 0x7ffd414f35c0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:365 (0x7f3ca04d2cd0 @ 10)
Aug 30 00:56:27 lambda org.gnome.Shell.desktop[27454]: #4 0x7ffd414f3530 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:350 (0x7f3ca04d2c48 @ 100)
Aug 30 00:56:27 lambda org.gnome.Shell.desktop[27454]: #3 0x7ffd414f3480 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:337 (0x7f3ca04d2bc0 @ 1626)
Aug 30 00:56:27 lambda org.gnome.Shell.desktop[27454]: #2 0x7ffd414f3330 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (0x7f3ca04d2b38 @ 54)
Aug 30 00:56:27 lambda org.gnome.Shell.desktop[27454]: #1 0x55d83dfc6e10 i   resource:///org/gnome/shell/ui/tweener.js:112 (0x7f3ca04c8e68 @ 37)
Aug 30 00:56:27 lambda org.gnome.Shell.desktop[27454]: #0 0x55d83dfc6e98 i   resource:///org/gnome/shell/ui/background.js:718 (0x7f3ca020f450 @ 22)
Aug 30 00:56:27 lambda org.gnome.Shell.desktop[27454]: == Stack trace for context 0x55d83dbfd4c0 ==
Aug 30 00:56:27 lambda gnome-shell[27454]: Object Meta.Background (0x55d83eb0c7a0), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
Aug 30 00:48:00 lambda org.gnome.Shell.desktop[23952]: ###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer Processing error: message was deserialized, but the handler returned false (indicating failure)
Aug 30 00:48:00 lambda org.gnome.Shell.desktop[23952]: IPDL protocol error: Handler returned error code!
Aug 30 00:48:00 lambda org.gnome.Shell.desktop[23952]: ###!!! [Parent][DispatchAsyncMessage] Error: PLayerTransaction::Msg_ReleaseLayer Processing error: message was deserialized, but the handler returned false (indicating failure)
```

I don't know if these errors are related. I'll try to replicate and I'll get back at you.

**Comment by pabloi** [comment]
I'm sorry to report that I haven't been able to find anything conclusive. The issue still happens and it appears to me that it happens more often if timepp is enable than if it is not. However, none of the stack traces I get from journalctl appear to relate to timepp.

My latest stack trace starts with:
gnome-shell[1191]: Object St.Bin (0x55d3ef44ee10), has been already finalized. Impossible to get any property from it.
And it lead to gnome-shell being restarted a minute later. It sounds similar to the issues being discussed here: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1, so perhaps it is the shell's fault.

**Comment by zagortenay333** [comment]
@pabloi , Could you check now? I think this might have been solved in the latest commit.

**Comment by pabloi** [comment]
Sure, I just installed the latest GitHub version and will let you know what I find. Thanks for looking into this!

**Comment by zagortenay333** [comment]
@pabloi any news?

**Comment by pabloi** [comment]
So far so good!, I haven't had any further crashes on Ubuntu 18.04.

I tried installing on Ubuntu 18.10 (gnome 3.30) but I can't seem to get the
gnome-shell to see the extension (it is as if it wasn't there).

I'll keep you posted with any further updates.

**Comment by zagortenay333** [comment]
I did upload the extension without updating the metadata file, but that's fixed now, so not sure why you can't install it on 3.30.

I'm gonna close this since it has to do with issue #75 and that one has been fixed.
