### ISSUE TITLE
interruptions in tracker

### ISSUE THREAD

**Issue by alperyilmaz** [zagortenay333/cronomix#74]
I started using the extension yesterday and it worked fine. I integrated pomo with tracker via `tracker_id` and in the tracker csv file, I can see 25 min stretch of work and 5 min of gaps for break (first two entries in data below).
But this morning the tracker started to record the block of times with interrupted segments without gaps. Below is an example entry to describe what I mean:

```
2018-08-28, 03:17:40, ++, "+coding", 00:33:39..00:58:39||01:03:41..01:28:40||01:33:42..01:53:12||01:53:12..01:53:34||10:14:10..10:17:40||10:17:40..10:19:10||10:19:10..10:23:40||10:23:40..10:24:10||10:24:10..10:39:10||10:44:11..10:44:15||11:50:16..11:52:47||11:52:47..11:57:17||11:57:17..11:58:47||11:58:48..12:00:19||12:00:19..12:01:49||12:01:49..12:06:20||12:06:20..12:10:20||12:10:20..12:10:50||12:10:50..12:12:50||12:12:51..12:13:52||12:13:52..12:15:11||12:33:35..12:35:05||12:35:07..12:38:07||12:38:07..12:41:07||12:41:07..12:45:07||12:45:07..12:46:37||12:46:37..12:58:34||13:03:36..13:08:06||13:08:06..13:09:36||13:09:36..13:14:36||13:14:36..13:16:36||13:16:36..13:19:06||13:19:08..13:22:39||13:22:39..13:27:40||13:27:40..13:28:35||13:33:37..13:41:08||13:41:08..13:41:38||13:41:38..13:42:35||13:42:46..13:44:16||13:44:16..13:45:16||13:45:18..13:45:48||13:45:48..13:46:48||13:46:48..13:47:18||13:47:18..13:47:48||13:47:48..13:49:18||13:49:18..13:49:48||13:49:48..13:50:48||13:50:48..13:51:48||13:51:48..13:52:48||13:52:48..13:53:48||13:53:48..13:54:48||13:54:48..13:55:48||13:55:48..13:56:48||13:56:48..13:57:48||13:57:48..13:58:18||13:58:18..13:58:48||13:58:48..14:00:48||14:00:48..14:01:18||14:01:18..14:01:48||14:01:48..14:01:48..
``` 

I thought the pomo was causing the problem maybe due to dbus communication, thus I stopped the pomo and started the task from todo kanban screen (clicked the small play icon) but the recording was still interrupted.

The total time recorded is probably correct, so there's no calculation error. But the tracker file become quite noisy, as does the report

![noisy report](https://i.snag.gy/qfKx47.jpg)

How can I troubleshoot this problem?

thanks (and btw the extension is great!, big kudos)

**Comment by zagortenay333** [comment]
Yeah, that looks really ugly.

Pomo is not communicating using dbus since it's part of the same extension.

I'm not writing into the tracker file cases when you have a zero-length interval like `01:00..01:00`, but I'm not reducing intervals of the type `start..01:00||01:00..end` to `start..end` (which I should probably.)
But I've no clue why you have those types of intervals in the first place; I don't know what's causing the interrupts.

Are you perhaps using that script that starts/stops the tracker as you switch workspaces?

To help debugging you can run `journalctl /usr/bin/gnome-shell -f -o cat` in a terminal and monitor the output as you use timepp.

**Comment by alperyilmaz** [comment]
Hi @zagortenay333, thanks for the reply.
I don't have a workspace switch related script (as far as I know). 
I ran `watch tail -1 'TODAY__time_tracker.csv'` in one terminal and then ran `journalctl /usr/bin/gnome-shell -f -o cat` in another. 

Below is the intervals (and interrupts) and on the bottom you can see the log for the corresponding time period. During that time, I didn't change workspace or window, I didnt click anything or wrote anything.  So it must be something else triggering this behavior. 

Is there any other tool to watch or monitor gnome-shell events (like `gdb` or `strace` maybe?) I guess gnome-shell extensions are using javascript underneath, maybe a javascript specific debugging or monitoring tool?

I wish I was more expert in this field so that I cannot debug the problem myself with right tools.

```
||21:54:37..21:55:38||21:55:38..21:57:08||21:57:08..21:58:08||21:58:08..21:59:08||
21:59:08..21:59:38||21:59:39..22:01:10||22:01:10..22:06:10||22:06:12..22:08:12||
22:08:12..22:11:12||22:11:12..22:11:42||22:11:42..22:13:42||22:13:44..22:15:14||
22:15:14..22:16:44||22:16:44..22:17:14..
```

```
Aug 28 22:05:38 n550 gnome-shell[26179]: Object Meta.Background (0x7fe41c02ad10), has been already deallocated - impossible to access to it. This might be caused by the fact that the object has been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs
Aug 28 22:05:38 n550 org.gnome.Shell.desktop[26179]: == Stack trace for context 0x55eecbda64c0 ==
Aug 28 22:05:38 n550 org.gnome.Shell.desktop[26179]: #0 0x55eecc3f57a8 i   resource:///org/gnome/shell/ui/background.js:718 (0x7fe41010f450 @ 22)
Aug 28 22:05:38 n550 org.gnome.Shell.desktop[26179]: #1 0x55eecc3f5720 i   resource:///org/gnome/shell/ui/tweener.js:112 (0x7fe4105c8e68 @ 37)
Aug 28 22:05:38 n550 org.gnome.Shell.desktop[26179]: #2 0x7fffa95ff360 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:208 (0x7fe4105d2b38 @ 54)
Aug 28 22:05:38 n550 org.gnome.Shell.desktop[26179]: #3 0x7fffa95ff4b0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:337 (0x7fe4105d2bc0 @ 1626)
Aug 28 22:05:38 n550 org.gnome.Shell.desktop[26179]: #4 0x7fffa95ff560 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:350 (0x7fe4105d2c48 @ 100)
Aug 28 22:05:38 n550 org.gnome.Shell.desktop[26179]: #5 0x7fffa95ff5f0 b   resource:///org/gnome/gjs/modules/tweener/tweener.js:365 (0x7fe4105d2cd0 @ 10)
Aug 28 22:05:38 n550 org.gnome.Shell.desktop[26179]: #6 0x7fffa95ff6e0 b   resource:///org/gnome/gjs/modules/signals.js:128 (0x7fe4105d2230 @ 386)
Aug 28 22:05:38 n550 org.gnome.Shell.desktop[26179]: #7 0x7fffa95ff790 b   resource:///org/gnome/shell/ui/tweener.js:244 (0x7fe4105cf808 @ 159)
Aug 28 22:05:38 n550 org.gnome.Shell.desktop[26179]: #8 0x7fffa95ff7f0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7fe4105b5de0 @ 71)
Aug 28 22:05:38 n550 org.gnome.Shell.desktop[26179]: #9 0x7fffa95ff890 b   resource:///org/gnome/shell/ui/tweener.js:219 (0x7fe4105cf780 @ 15)
Aug 28 22:11:11 n550 org.gnome.Shell.desktop[10756]: ###!!! [Parent][DispatchAsyncMessage] Error: PClientSourceOp::Msg___delete__ Route error: message sent to unknown actor ID
```

**Comment by zagortenay333** [comment]
Hmm, I really don't know..
Thing is, it looks like a bug in the extension, but it's the kind of bug I should have on my machine too. It also seems that the interrupts are more or less random too.

What version of gnome-shell are you on and are you using the github version of the extension?
There is an option in the setting to resume tracking when the timer is interrupted; is it active?

**Comment by alperyilmaz** [comment]
Hi,
my gnome-shell version is `GNOME Shell 3.28.3` and I installed from github.

In the extension, oniy pomo and todo/tracker are active, others are disabled. For the todo/tracker, I have `Resume tracking after abrupt restart` option, which is ON.

**Comment by zagortenay333** [comment]
Could you disable that option and see whether the tracker will stop? If the tracker gets interrupted that will cause it to start again. Again, monitor that journalctl thing above.

**Comment by alperyilmaz** [comment]
I turned that option off and restarted gnome-shell (just in case).. then ran the journalctl command and watched the tracker file. After 5 mins, what happened is, the tracker stopped and it didnt restart. After that I restarted the same task, again it recorded for very shot time and then stopped.

So, something is causing the tracker to stop?

**Comment by alperyilmaz** [comment]
I forgot to mention, journarctl output didnt output anything coinciding with the tracker stop.

**Comment by zagortenay333** [comment]
Oh, boy. That means we're gonna have to debug this the old-fashioned way; we're gonna have to liter the code with a bunch of log prints to figure out what's going on...

I don't have time right now though; tomorrow. That's if you're up for it.

**Comment by alperyilmaz** [comment]
Sorry for taking your time.. Yes, I'm up for it.. 

But, before taking your time so much, can you suggest a way to track/monitor global events in gnome-shell? If I can debug external events as much as possible, that might save you (and me) time.  Because my gnome-shell is not as stable as it should be. (my journalctl output, for 2 months, has 3.5 million lines related to gnome-shell and org.gnome.Shell.desktop, most of which are repeats)

**Comment by zagortenay333** [comment]
You can check this out: https://wiki.gnome.org/Projects/GnomeShell/Debugging

But it's too much of a hassle. I don't think it would help anyway.

**Comment by alperyilmaz** [comment]
yeah, both C and JS debugging is causing pauses, freezing the gnome-shell.. That's not needed in this case..

**Comment by zagortenay333** [comment]
Btw, would you mind disabling pomodoro from the settings and then restarting gnome-shell. Do the interrupts still occur?

**Comment by alperyilmaz** [comment]
Hi,
I disabled pomo and then restarted gnome-shell and track a task, here are the intervals:

```
01:09:09..01:10:09||01:10:09..01:18:39||01:18:39..01:20:39||01:20:39..01:24:09||01:24:09..01:25:39..
```

**Comment by alperyilmaz** [comment]
just letting you know, I installed ubuntu 18.04 in VirtualBox and testing your extension in it.. So far it's working without problems.. Next, I'll install the extensions in my machine one by one to see if any of them interfere..

I'll keep you posted..

**Comment by alperyilmaz** [comment]
Hi again, I tried another method, disabling almost all extensions in my current machine. That still didn't resolve the issue. As I mentioned, my `gnome-shell` recently got quite unstable thus I looked into it, and found out wayland has slipped through as display manager during upgrades. I got back to gdm3.. however, that also didn't resolve the issue.

I guess I should better not take much of your time for debugging the issue.. I can write a short script to clean and merge interrupted intervals in csv files..

**Comment by zagortenay333** [comment]
Insert a log print here:
https://github.com/zagortenay333/timepp__gnome/blob/8bbf83ce16bedb6e810b58e9807687469263a712/sections/todo/time_tracker.js#L506-L515

```js
 stop_all_tracking: function (do_write_daily_csv_file = true, close_intervals = true) { 
     log(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> " + do_write_daily_csv_file + " " + close_intervals);
     if (! this.csv_dir) return; 
```
Then check the logs with that jornalctl command. Let's first see if this is the func that is causing the interruptions.

**Comment by alperyilmaz** [comment]
Hi again, before trying the debug command you've sent, I tried something else. My todo and tracker files were under Dropbox folder (`Dropbox/Apps/Simpletask App Folder/` to be more exact) which is also accessed via an app in my phone. 

I moved the files to another location and now it's working fine, there are no interruptions. So, it looks like the problem was having the files under Dropbox syncing folder.

**Comment by zagortenay333** [comment]
Ohhh!! So what is happening is:
- Dropbox is updating the csv file somehow (maybe a timestamp or something else while syncing.)
- I interrupt the tracker each time the csv file gets updated externally. (Say you update the csv file with a text editor, the tracker will stop.)
- The option `Resume tracking after abrupt restart` kicks in and restarts the tracker immediatelly leaving you with those weird interruptions.

I guess the only fix is to clean up the csv file whenever I see something like `start..01:00||01:00..end`. For now you're not gonna be able to keep the csv files in Dropbox.

**Comment by zagortenay333** [comment]
Maybe I can detect what the heck dropbox is doing and _not_ react to it.

**Comment by zagortenay333** [comment]
Could you check whether it works now, @alperyilmaz ?

**Comment by alperyilmaz** [comment]
It works.. After removing the folder from Dropbox folder, it works fine..

**Comment by mbroedl** [comment]
@zagortenay333 I observe the same issues. I don't use dropbox, but to me these interruptions occur everytime I change the **todo.txt** file (changing the csv file manually just overwrote it while in tracker mode).
It seems that only changes to that file _externally_ (i.e. with other programs, such as changing the order of two unrelated tasks in the file) cause the tracker to interrupt, but not when using the app itself.

Hope this helps.

**Comment by zagortenay333** [comment]
@mbroedl That's how it's supposed to work. Don't edit the file while you're time-tracking.

**Comment by zagortenay333** [comment]
@alperyilmaz Ah, I meant to say could you put it back into the dropbox folder and see whether it works now?
