### ISSUE TITLE
Kanban not working

### ISSUE THREAD

**Issue by fragsalat** [zagortenay333/cronomix#76]
Hey there,

maybe I'm doing it wrong but I added this extension to my gnome shell, created a clean todo.txt added `kan:*general|Open|Progress|Done` to the file and could the the kanban board. Adding a task in any column results in a task in the first column. Moving the task to another column doesn't work as well for me.
Beside that the extension seem to work properly.

My gnome shell version is: 3.28.3-0ubuntu0.18.04.2

Any Idea what I'm doing wrong or how I can help you to figure out what the problem is?

Best
FragSalat

**Comment by zagortenay333** [comment]
You're not using it correctly; it is a bit tricky. The names of columns can be:
1. projects (with a + prefix)
2. contexts (with a @ prefix)
3. priorities (a capital letter in parens (A) or (_) to mean no priority or closed)
4. normal strings like in your example (these are kitchen sink columns with a title)
5. the char $ (a kitchen sink column with no title)

Basically, you specified 3 kitchen sink columns with a title, so everything goes into the first one.

If those are projects, then type `kan:*general|+Open|+Progress|+Done`.  
If they are contexts `kan:*general|@Open|@Progress|@Done`.

**Comment by fragsalat** [comment]
Haha ok this was absolutely not clear for me.
So it just adds  projects, contexts or priorities to the task and group it by them into the columns.
Is it possible to start the timer when moving a task into a certain column? If not I probably will stick to the simple list.

**Comment by zagortenay333** [comment]
Why would you start the timer?

**Comment by fragsalat** [comment]
Like in my example in a kanban board I start working on a task and when it's at the end of the board it's done. But I misunderstood this kanban feature. It's actually just clustering things into columns and not tracking a progress.
Anyway thanks for the clarification :)

**Comment by zagortenay333** [comment]
Yeah, it's for organizational purposes. :)
