### ISSUE TITLE
No setting for the time tracker directory

### ISSUE THREAD

**Issue by annargrs** [zagortenay333/cronomix#77]
The tutorial says that the time tracking should start with "play" button in the task list. However, for that to happen the directory for saving time tracking info must first be set. [This page](https://github.com/zagortenay333/timepp__gnome/blob/master/data/tracker_spec.md) specifies the directory structure. However, the current version of the extension does not seem have any such setting in "Time tracker" section, or anywhere else. 

Where should this setting be accessed? Perhaps the tutorial should be clarified?

**Comment by zagortenay333** [comment]
You choose the tracker directory in the same place you chose your todo.txt file, the popup menu.  
Click the file icon; the one where the search and other icons are.  
You'll see 4 text-boxes: for the name, todo.txt file path, the done.txt file path, and the tracker dir path.

**Comment by annargrs** [comment]
Thanks, found it! Maybe it's worth adding that to the tutorial.
