### ISSUE TITLE
How to delete single completed tasks?

### ISSUE THREAD

**Issue by v-marinkov** [zagortenay333/cronomix#78]
How  do I delete single completed tasks? When I click on "clean completed tasks" it deletes all of them regardless of their project, context, etc. and regardless of whether I click the radio toggle for "Delete all completed tasks".
Thanks!

**Comment by zagortenay333** [comment]
Click on the icon to edit the task, and you'll see that it has a delete button down there.

**Comment by v-marinkov** [comment]
Right, I was hoping there was some bulk select utility. Thanks anyway.
Finally, was is the purpose of the "Delete all completed tasks" radio button?

**Comment by zagortenay333** [comment]
But you have a bulk select utility, the checkbox. You check the tasks for completion and then you can delete them all at once or archive them all at once.
