### ISSUE TITLE
Show single icon in panel + Show in seperate menu

### ISSUE THREAD

**Issue by Vaesper** [zagortenay333/cronomix#8]
I'd like all time related functions (timer, stopwatch, pomodoro, alarm) grouped under 1 icon, but the todo list seperate, however there is currently no way to do that. When I select "Show single icon in panel" the "Show in seperate menu" option on my todo list is ignored. Honoring this setting would really help optimize my scarce panel space.

**Comment by zagortenay333** [comment]
Tbh, I don't know why I didn't make it work that way to begin with.

This should be done with the latest commits; let me know if it works correctly.

**Comment by zagortenay333** [comment]
Actually hold on. There's bug here..

**Comment by Vaesper** [comment]
LGTM
