### ISSUE TITLE
Get list of tracked task via dbus

### ISSUE THREAD

**Issue by daroczig** [zagortenay333/cronomix#80]
This is such a great app, thanks!

Any chance to add an option to show the currently active task in the panel if the time tracker is on? Currently, if the time-tracker is active, then the color of the checkmark changes, but it would be great if the actual task name could also show up next to it.

**Comment by zagortenay333** [comment]
Srry, not gonna do this for 3 reasons:

1. There isn't really such a thing as a task name, only the text of it. If the task is long, it would get ugly.
2. It's possible to track multiple tasks at once, so making this work wouldn't be easy.
3. I don't need this feature.

**Comment by daroczig** [comment]
Got it, thanks for the quick feedback. I'm not really worried about (1) and (2), so I wouldn't mind implementing this -- even outside of the `time++` extension. Any chance to query the tasks being tracked via `dbus` or other ways?

**Comment by zagortenay333** [comment]
@daroczig , I updated the time-tracker dbus api. Now you can get a list of all tracked tasks/projects as well as monitor when a task gets tracked/untracked:
https://github.com/zagortenay333/timepp__gnome/blob/565fa706944d7242c4b265e130c669502f836985/dbus/time_tracker_iface.xml#L22-L46
https://github.com/zagortenay333/timepp__gnome/blob/565fa706944d7242c4b265e130c669502f836985/dbus/scripts/examples#L38-L82

**Comment by daroczig** [comment]
This is fantastic, thank you so much! :100:

**Comment by daroczig** [comment]
If anyone might want to do something like myself:

- sync Jira tickets from the current Sprint to `todo.txt` using the Jira ticket id as the first word of the tasks
- show the currently tracked Jira ticket id in the panel

Then I'm using [Argos](https://github.com/p-e-w/argos) and a [tiny Python script](https://gist.github.com/daroczig/802f956a33194fd181e298ea204185b1) to print the Jira ticket id of the currently tracked task.

Demo:

![image](https://user-images.githubusercontent.com/495736/48318517-7ad67c00-e602-11e8-9685-6a6544298c5c.png)
