### ISSUE TITLE
After last update, pomodoro section is broken

### ISSUE THREAD

**Issue by fndercole** [zagortenay333/cronomix#81]
On ubuntu 18.04, After update, pomodoro section is broken.

I don't know what is the info needed for troubleshooting.

I updated from gnome extension web. Then i uninstalled and cloned from github repo, with the same problem. All sections works except pomodoro.

**Comment by zagortenay333** [comment]
Fixed. Will take a while to update on the extensions site though...

**Comment by fndercole** [comment]
Thanks
