### ISSUE TITLE
[Feature request] Don't show notifications

### ISSUE THREAD

**Issue by rruizt** [zagortenay333/cronomix#82]
Hello,

I normally use this extension with the notification sound and I don't need the visual notification. Would it be possible to add a new option to the "Notification style" set as None that will not show any notification?

Current behavior:
Two options in Notification Style: Standard and Full screen. Both show some sort of visual notification

Desired behavior:
Three options in Notification Style: Standard, Full screen and None. The two first work as usual, None works by not showing any notification at all.

Thank you!

**Comment by zagortenay333** [comment]
You mean a _sound only_ style? No notification wouldn't make sense.

**Comment by rruizt** [comment]
@zagortenay333 That is my usecase indeed, but I would leave the choice to the user.

I can imagine that some people may look only to the numbers on the timer and don't want to be interrupted if it reaches to 0.

**Comment by zagortenay333** [comment]
I added this feature. Let me know whether it works correctly.

**Comment by rruizt** [comment]
It works like a charm!

Thank you!
