### ISSUE TITLE
Pomodoro menu bar icon and functionality is gone from latest version

### ISSUE THREAD

**Issue by sardaukar** [zagortenay333/cronomix#84]
Pomodoro icon is gone and clicking the space where the icon should be shows an empty drop down menu as well. I'm on Arch, Gnome 3.30.2

**Comment by zagortenay333** [comment]
Are you using the github version?

**Comment by sardaukar** [comment]
No, the extensions.gnome.org one - should I use the github one?

**Comment by zagortenay333** [comment]
Yes. The issues is fixed, but the extensions site is not update yet.

**Comment by sardaukar** [comment]
OK, thanks!
