### ISSUE TITLE
Pressing task edit opens link

### ISSUE THREAD

**Issue by razcore-rad** [zagortenay333/cronomix#87]
OS: Ubuntu 18.10
Time++: master branch, commit 14bc428b11a6d6ca74ddd369f38a3cf12ebffc8e

I've only tried web links, don't know if it's the same for file links.

![image](https://user-images.githubusercontent.com/1177508/50371301-b29cf000-05c0-11e9-83fc-5868c3aa8ce2.png)

**Comment by zagortenay333** [comment]
Should be fixed now.
