### ISSUE TITLE
Where to set csv file or dir

### ISSUE THREAD

**Issue by KokeCacao** [zagortenay333/cronomix#88]
I know this question may be stupid, but I spend 30min trying to figure it out where to set the csv file.

# What I tried
  1. Install through https://extensions.gnome.org/extension/1238/time/ (using Ubuntu 18.04)
  2. Creating a task file
![image](https://user-images.githubusercontent.com/13199775/50747912-78f4f780-1204-11e9-9fee-d38e61815db4.png)
  3. Creating a task
![image](https://user-images.githubusercontent.com/13199775/50747930-9924b680-1204-11e9-9e13-fcca3eba73f1.png)
  4. Trying to find the setting in `setting`
![image](https://user-images.githubusercontent.com/13199775/50747957-b6598500-1204-11e9-8986-73afede450dd.png)
  5. Click `start timing`, but I got a warning: 
![image](https://user-images.githubusercontent.com/13199775/50747974-dd17bb80-1204-11e9-8aee-e0139bd631e9.png)

# The Question
Where should I set the csv file or dir?

**Comment by zagortenay333** [comment]
In the same place you chose the todo and done files you select a csv directory, and timepp will automatically make the csv files inside of it.

Above you specified a file `TODO/gnome_time.csv` instead of just a directory `TODO/`.

**Comment by PenelopeFudd** [comment]
I'm having this problem too.  

When I initially set up the extension, it only had a panel for setting the filenames and directories.  Once I entered a filename for the todo file and saved it, that panel went away.  

Now, when I right-click on the checkmark icon and select 'Open Settings', there are 6 different tabs, none of which show the filename or directory names.  Perhaps I have to uninstall and reinstall the extension to get back to that panel?

Thanks.

**Comment by MarkoPaasila** [comment]
> I'm having this problem too.
> 
> When I initially set up the extension, it only had a panel for setting the filenames and directories. Once I entered a filename for the todo file and saved it, that panel went away.
> 
> Now, when I right-click on the checkmark icon and select 'Open Settings', there are 6 different tabs, none of which show the filename or directory names. Perhaps I have to uninstall and reinstall the extension to get back to that panel?
> 
> Thanks.

I found the answer [here](https://github.com/zagortenay333/timepp__gnome/issues/77#issuecomment-435184159)

**Comment by PenelopeFudd** [comment]
I saw #77, but there was no way for me to get back to the panel with the text boxes; it was gone.

It seems like I had to find the configuration file and edit it manually to get things to work right.

**Comment by zagortenay333** [comment]
You click the filename icon to get to the list of your files:
![image](https://user-images.githubusercontent.com/11144630/63511096-884d5a80-c4e0-11e9-9a9f-7963070f0f3b.png)

This gets you back to this list:
![image](https://user-images.githubusercontent.com/11144630/63511196-d2ced700-c4e0-11e9-9228-c6a2b9a86491.png)

Hover over one of these cards and an edit icon will appear next to where that green checkmark is.
