### ISSUE TITLE
Git master version crashes on unlock.

### ISSUE THREAD

**Issue by Vaesper** [zagortenay333/cronomix#9]
On archlinux with gnome 3.24 on wayland. Not exactly sure how to provide debug logs if this is not enough info to reproduce.

**Comment by zagortenay333** [comment]
Don't have this issue.

Check the output of :
```
journalctl /usr/bin/gnome-shell -r | less
```
You can use `/` to search for `timepp` or `time` and see if there are any bugs. `q` to quit.

**Comment by zagortenay333** [comment]
What do you mean crashes?

**Comment by zagortenay333** [comment]
Btw, are you sure you have the latest version from github?  I did fix a bug today.

**Comment by Vaesper** [comment]
Yes, most definitely, did a `git pull` right before posting the issue to make sure I did not miss a bugfix - was already up to date. And with crashes I mean that after entering my password on the lockscreen, the screen freezes for some some 10s of seconds before dumping me back to the login screen. Logging in again shows me a completely new session (ie. all my applications were closed). I know that on Wayland you cannot restart gnome-shell without restarting the session, so maybe someone on X11 isn't so clearly aware of it.

I cannot immediately find a clear error using `journalctl`.

**Comment by zagortenay333** [comment]
Could you try the latest version now? I added a commit that might fix it.

Also, if it doesn't work, can you revert back to this commit:
https://github.com/zagortenay333/timepp__gnome/tree/a4fe5e5ff6f297fa3040c84ca796f92b8d2d6555

This is before I introduced that feature you requested.

**Comment by Vaesper** [comment]
Can confirm issue still exists with that latest one, will try pre-unified icon now (I was on the extensions.gnome.org version before).

**Comment by zagortenay333** [comment]
Since I cannot reproduce it, you're gonna have to go commit after commit back in time until you find the  commit that introduced the regression.

**Comment by Vaesper** [comment]
Working on it. Hard to predict when it triggers too, as current master managed to not break once, but then did break a bit later...

**Comment by Vaesper** [comment]
So far a4fe5e5ff6f297fa3040c84ca796f92b8d2d6555 seems to not crash.

**Comment by zagortenay333** [comment]
Yeah, that's before the feature.

Could you try the latest master yet again. Srry that I bother you, but since I can't reproduce it I need your help  here.

**Comment by Vaesper** [comment]
No problem, it's entirely in my selfish interest to get this fixed, since my requested feature needs it ;)

Is there any way to force reload an extension after manually updating without restarting the shell entirely?

**Comment by zagortenay333** [comment]
Nope. Wayland doesn't allow for shell restarts? Yikes

**Comment by Vaesper** [comment]
Not without killing the session. I understand it's a feature in terms of security...

**Comment by zagortenay333** [comment]
Will continue workin' on this tomorrow, btw.

**Comment by zagortenay333** [comment]
Did you try the latest version again?

**Comment by Vaesper** [comment]
Tried it last night, seems to crash. Thoroughly testing a4fe5e5ff6f297fa3040c84ca796f92b8d2d6555 now to make sure it was indeed something after that.

**Comment by zagortenay333** [comment]
Yeah, that's a good idea.

Btw, does this bug happen consistently? Also, show me the the general tab in your settings (screenshoot.)

Oh, and I added another commit to master, might wanna try again with latest. I did notice some error on my machine regarding the fullscreen, maybe that was the culprit.

**Comment by Vaesper** [comment]
Bug happens mostly consistently, but not entirely so... I have not figured out the conditions that trigger it.

![Screenshoot](https://i.imgur.com/rtwD4Vq.png)

I'll try again with latest soon-ish.

**Comment by zagortenay333** [comment]
Did you manage to replicate the bug that commit?

**Comment by Vaesper** [comment]
a4fe5e5ff6f297fa3040c84ca796f92b8d2d6555 -> no crash

fb19c26175ebe402381cc796af29ad8dc7e2d61a -> crash

[Journal log with personal stuff redacted](https://0bin.net/paste/p6nkffjql1AzXqrc#JDKnjqdoaiY2sf91baAGDE64hHmRGXS1GkdVfhcCMIE)

**Comment by zagortenay333** [comment]
Ah, you got the journalctl finally!

Can you show me the output of journalctl on the a4fe5e5 commit and the journalctl on the commit right after it 6082b981160f2eac1661232bc40e53d3c6a2237a ?

**Comment by Vaesper** [comment]
Sure, you'll have to bear with my slowness - having to interrupt my other activities by restarting my session makes it somewhat annoying to debug. I found an extension that was supposed to help me out here but unfortunately it doesn't work in this case (nls1729/acme-code#27).

**Comment by zagortenay333** [comment]
No problem, man. I annoyed enough already XD. No rush.

Btw, I have a feeling I solved the problem  in latest master as I was able to find a nasty bug which gets triggered when locking/unlocking.

The only difference seems to be is that on your machine it caused a crash, but on mine it didn't. Again, not 100% sure.

**Comment by Vaesper** [comment]
Now it crashed on a4fe5e5ff6f297fa3040c84ca796f92b8d2d6555 too 😕 

https://0bin.net/paste/8bPD9ZMD-dlO2q4z#OlZup5R7Zsiz3cuoZTvDMK4J9I0HACYkxPR4Fo4OCsk

**Comment by zagortenay333** [comment]
Actually that's good. It means that the bug I found is probably it since it has been around for a while. Try out master.

**Comment by Vaesper** [comment]
5a96b20ee0ed49dca0595c5b2a88c5ca22f5a766 -> crash: [Journal log](https://0bin.net/paste/diSSz-f6XiGZEQZA#xMHMGY9YLfxhyJqfiNHeU76qUZaWGeCpa5cWtNOM+di)

Going to remove the git version and reinstall from e.g.o to sanity check.

**Comment by zagortenay333** [comment]
Show me the journal output after you disable the extension.

**Comment by Vaesper** [comment]
I think [this](https://0bin.net/paste/UxAKKqB7spL6Sgr+#GrwWtDx1ZavKAbjrjQQTZpL4+rRMC5SML1HYyBsM6mU) is the right part of the log judging by the timestamps.

**Comment by zagortenay333** [comment]
From what commit is that log?

**Comment by Vaesper** [comment]
That's from when I clicked "remove" in the tweak tool. I had 5a96b20ee0ed49dca0595c5b2a88c5ca22f5a766 running at the time.

**Comment by zagortenay333** [comment]
I'm at my wit's end.

I definitely did fix an annoying bug in that last commit, so that's nice. What's causing your bug I've no clue.

**Comment by Vaesper** [comment]
Running e.g.o version also gave me the issue when it didn't in the past. I'm now trying out if some other extension update snuck past me and is causing the issue... Going to keep trying until I've got the e.g.o version running without issue and then switch to master to check if that then also doesn't break...

**Comment by zagortenay333** [comment]
Disable all other extension before you test this one. That's the simplest way to verify that it is this ext that causes it.

**Comment by Vaesper** [comment]
It's proving somewhat hard to hunt down, especially considering that it doesn't happen every screen unlock... It seems it may even be some sort of interaction between different extensions. I'll close for now and not reopen unless I find out there time++ is (one of) the culprit(s).

**Comment by zagortenay333** [comment]
Like I said, either disable all other extension or only disable time++ and see if the bug reappears.

**Comment by Vaesper** [comment]
Complete Heisenbug, disabling all extensions except one made it disappear, enabling them again one by one never made it reappear even when in the same state as when it appeared before... Tested Time++ master, works completely fine now.

**Comment by zagortenay333** [comment]
Uff, that's kinda scary :fearful: Hopefully it doesn't reappear.

**Comment by zagortenay333** [comment]
Bump. Curious, have you had this bug appear again?

**Comment by Vaesper** [comment]
Nope, not at all.
