### ISSUE TITLE
Where is TODO config saved?

### ISSUE THREAD

**Issue by Slamdunk** [zagortenay333/cronomix#90]
Hi, the first time I've started the TODO Section it asked me where to place my todo.txt.

Now I want to move it to another place, but I can't find any configuration to edit in the GUI, nor grepping in my home directory.

Where is config saved? How can I move the todo.txt file that the app uses?

**Comment by zagortenay333** [comment]
You move your txt file and go into the place where you control the files (where you added the first time) and update the entry or add another one.

**Comment by Slamdunk** [comment]
Hi, if I do so the app automatically recreate an empty file instead of asking :disappointed:

**Comment by zagortenay333** [comment]
Yeah, it's a little awkward like that. I'm monitoring for changes to the file and if it gets deleted I make an empty one. After you moved your files and updated the extension in the popup menu, just delete the empty ones.
