### ISSUE TITLE
Issue with panel item mode for todo/time tracker

### ISSUE THREAD

**Issue by theychx** [zagortenay333/cronomix#94]
Hi
I prefer the "Icon only" setting, however upon adding a new task or changing the status of an existing task, the setting is always immediately returned to both icon and text (without it actually changing in the settings window).

(using gs 3.30.2)

**Comment by ftostevin** [comment]
Due to this line: https://github.com/zagortenay333/timepp__gnome/blob/3be06b0677bdfe6f220a61f4b26f411762d20f30/sections/todo/MAIN.js#L518
Commenting it out prevents the text from being added

**Comment by zagortenay333** [comment]
I removed that line. I'm not entirely sure why it was there. Hopefully I didn't break anything...
