### ISSUE TITLE
Gnome 3.32 compat

### ISSUE THREAD

**Issue by koug44** [zagortenay333/cronomix#97]
Extension does not works on Gnome 3.32 (Archlinux here)

**Comment by fxdave** [comment]
Same.
Here it is the error message if it helps: `Extension "timepp@zagortenay333" had error: Error: Property Gjs_Timepp_Timepp.content-box is not writable`

**Comment by mirko-laruina** [comment]
It should be working now, check my pull request #96.
If there are any problems let me know.

**Comment by koug44** [comment]
I confirm this fixes the issue for me

**Comment by mirko-laruina** [comment]
Nice, I don't particularly like the solution I've adopted for the icons, but at least it works :smile:

**Comment by mirko-laruina** [comment]
I've noticed the notification sound wasn't workingl.
I don't know if it is related to GNOME 3.32 or if it didn't work before too because I've never used that feature. Anyway, can you check on your side? 96c9ca9dfb644f09dfed84e3a9593ba7a0cab10b seems to fix

**Comment by fxdave** [comment]
@mirko-laruina Thanks but sound is not working yet.

**Comment by mirko-laruina** [comment]
@fxdave Can you edit `/lib/sound_player.js` at line 39-41, from
```javascript
            let file = Gio.file_new_for_uri(this.sound_uri);
            let player = global.display.get_sound_player();
            player.play_from_file(file, '', null);
```
to
```javascript
            global.log(this.sound_uri)
            let file = Gio.file_new_for_uri(this.sound_uri);
            global.log(file)
            let player = global.display.get_sound_player();
            global.log(player)
            player.play_from_file(file, '', null);
```

Open a terminal, launch `journalctl /usr/bin/gnome-shell -f -o cat`, restart GNOME shell (`Alt+F2` and then `r`) and set a timer. Can you paste here what you see after the timer is expired? It should be something like this, when working properly:
```
file:///home/archie/.local/share/gnome-shell/extensions/timepp@zagortenay333/data/sounds/bell.ogg
[object instance wrapper GType:GLocalFile jsobj@0x7f314c66ef40 native@0x55c80b04ce40]
[object instance wrapper GIName:Meta.SoundPlayer jsobj@0x7f314c66ea30 native@0x55c80e539200]
```

**Comment by fxdave** [comment]
@mirko-laruina Looks like the play method had never been called. There is no output given. I get only these:
Ignoring length property that isn't a number at line 1259, col 24
Ignoring excess values in shadow definition

**Comment by mirko-laruina** [comment]
This errors should be from GNOME itself.

It is quite strange, are you sure the notification sound is enabled in the settings?

**Comment by fxdave** [comment]
Okay I had to do a gnome-shell restart, it is working now.

**Comment by mirko-laruina** [comment]
Perfect! I think it is ready to be merged then :smile:

**Comment by zagortenay333** [comment]
This is fixed.
