### ISSUE TITLE
When lock the screen, using the timetracker, always get an error  and the time is not saved

### ISSUE THREAD

**Issue by NeoMorfeo** [zagortenay333/cronomix#98]
Using  archlinux, with Gnome 3.32 and the last version of the extesion, also the same with master code.

After lock the screen, with several time tracked on the tasks, it shows an error and the tracker csv is erased or truncated... :cry:  this is the journalctl output

```
mar 29 21:01:57 copernico gnome-shell[4826]: ERROR timepp (csv file):
                                             line: 3
                                             file: /home/neomorfeo/ToDo/Registros/TODAY__time_tracker.csv
mar 29 21:01:57 copernico gnome-shell[4826]: ERROR timepp (csv file):
                                             line: 2
                                             file: /home/neomorfeo/ToDo/Registros/TODAY__time_tracker.csv
mar 29 21:01:57 copernico gnome-shell[4826]: ERROR timepp (csv file):
                                             line: 1
                                             file: /home/neomorfeo/ToDo/Registros/TODAY__time_tracker.csv
mar 29 21:01:57 copernico gnome-shell[4826]: ERROR timepp (csv file):
                                             line: 0
                                             file: /home/neomorfeo/ToDo/Registros/TODAY__time_tracker.csv
mar 29 21:01:57 copernico gnome-shell[4826]: g_object_run_dispose: assertion 'G_IS_OBJECT (object)' failed
```

Can you please help with this? the extension is so good for my daily use and even at work.... but i need to keep that files.

**Comment by zagortenay333** [comment]
Can't help you right now; I'm neither using this extension nor do I have 3.32 installed.  
It doesn't help that gnome's error messages are more cryptic than Egyptian hieroglyphs..

Maybe @mirko-laruina is willing to help since he changed that ByteArray thing in the time-tracker file, which might have something to do with this.

Did you have the same bug on a previous version of gnome? Does it work correctly when you stop the tracker manually and not by locking the screen?

**Comment by NeoMorfeo** [comment]
@zagortenay333 hahaha! thanks anyway, but for me also is cryptographic...

I was not using your extension before 3.32, never needed till now... and looks just the thing i need to track  my work.

Answering your question, no, doesn't matter if i stop/pause the tracker before lock or not, the behavior is the same, the today file is "corrupted" and truncated.

**Comment by mirko-laruina** [comment]
Just made a PR ( #99 ), let me know if it works :smile:

**Comment by NeoMorfeo** [comment]
@mirko-laruina yes!!! now it's working fine! thanks!

@zagortenay333 looks the solution, so please merge :smile:

**Comment by zagortenay333** [comment]
Merged.
